export type Etape = {
  titre: string;
  duree: string;
  etapes: string[];
};

export type EtudePrelim = {
    q: string;
    r: string;
};

export type TP = {
  id: number;
  duree: string;
  titre: string;
  situation: string;
  objectif: string;
  materiel: string[];
  etudePrelim: EtudePrelim[];
  activitePratique: Etape[];
  securiteRangement: string[];
  pointsCles: string[];
};

function etape(titre: string, duree: string, etapes: string[]): Etape {
    return { titre, duree, etapes };
}

export const tpPremiere: Record<number, TP> = {
  1:{ id: 1, duree:'2h00', titre:'AS 207 • Accueillir le client et restituer le véhicule', situation:'Accueil client en atelier: prise en charge, recueil des symptômes, restitution et pédagogie.', objectif:'Réaliser un accueil et une restitution professionnels, avec OR et traçabilité.', materiel:['OR','Grille d’état','Tablette atelier','Documents garantie'], etudePrelim:[{q:'Mentions obligatoires OR ?',r:''},{q:'Différences devis/facture ?',r:''},{q:'Gestion d’un litige simple ?',r:''}], activitePratique:[ etape('Accueil','30 min',['Écoute active des symptômes.','Inspection visuelle conjointe.','Rédaction OR (immatriculation, km, demande).']), etape('Suivi','30 min',['Appel info délais/coûts.','Accord pour travaux complémentaires.']), etape('Restitution','40 min',['Explication facture.','Conseils entretien et planning.','Archivage et satisfaction.']) ], securiteRangement:['Protection des données','Archivage OR','Espace accueil propre'], pointsCles:['Clarté','Traçabilité','Posture pro'] },
  2:{ id: 2, duree:'1h30', titre:'UE 203 • Utilisation d\'un multimètre', situation:'Utilisation d’un multimètre sur maquette et véhicule.', objectif:'Mesurer V/Ω/continuité correctement et en sécurité.', materiel:['Multimètre','Pointes','Fusibles tests','Schéma simple'], etudePrelim:[{q:'Définir tension/courant/résistance et unités ?',r:''},{q:'Précautions avant mesure (contact/polarité/calibre) ?',r:''},{q:'Interprétation d’une chute de tension ?',r:''}], activitePratique:[ etape('Mesures V','25 min',['Repos/ralenti/consommateurs.','Chutes de tension connexions +/−.']), etape('Ω/continuité','30 min',['Test fusible (buzzer).','Mesure CTN/CTP.','Contrôle faisceau.']), etape('Validation','20 min',['Tableau mesures.','Erreurs fréquentes et prévention.']) ], securiteRangement:['Couper contact sur Ω','Pas de perçage isolants','Ranger cordons'], pointsCles:['Bon calibre','Polarité','Sécurité'] },
  3:{ id: 3, duree:'1h45', titre:'UE 202 • Contrôle circuit de démarrage', situation:'Diagnostic démarrage: batterie/câblage/contacteur/relais/démarreur.', objectif:'Identifier la cause d’un non-démarrage.', materiel:['Multimètre','Schéma','Pince ampèremétrique','Batterie/chargeur'], etudePrelim:[{q:'Chaîne +12V de la batterie au démarreur ?',r:''},{q:'Rôle relais démarreur ?',r:''},{q:'Appel de courant typique ?',r:''}], activitePratique:[ etape('Préliminaire','25 min',['Tension batterie >12,4 V.','Serrage/oxydation cosses.','Continuité masses.']), etape('Mesures','45 min',['Sortie contacteur (12 V en D).','Borne 50 démarreur.','Chutes tension câble + et masse.','Intensité démarrage 150–300 A.']), etape('Conclusion','25 min',['Batterie/câblage/relais/démarreur.','Préconisations.']) ], securiteRangement:['Batterie prudence','Ranger pinces','Tracer mesures'], pointsCles:['Batterie OK','Chutes révélatrices','Intensité haute'] },
  4:{ id: 4, duree:'2h00', titre:'UE 207 • Contrôle du démarreur', situation:'Contrôle démarreur sur véhicule et banc.', objectif:'Valider l’état du démarreur et de ses composants.', materiel:['Banc démarreur','Multimètre','Clés','Solénoïde/balais'], etudePrelim:[{q:'Constitution démarreur ?',r:''},{q:'Symptômes démarreur HS ?',r:''},{q:'Tests isolement/continuité ?',r:''}], activitePratique:[ etape('Dépose','30 min',['Débrancher batterie.','Dépose câbles/fixations.','Extraction démarreur.']), etape('Contrôles','40 min',['Résistances inducteur/induit.','Isolement masse.','Solénoïde/balais.']), etape('Banc','35 min',['Intensité à vide <80 A.','Bruit/rotation.','Test en charge.']), etape('Repose','15 min',['Couples serrage.','Test véhicule.']) ], securiteRangement:['Batterie off','Ranger banc','Nettoyage'], pointsCles:['Isolement','Balais','Validation banc'] },
  5:{ id: 5, duree:'1h45', titre:'UE 201 • Contrôle circuit de charge', situation:'Contrôle circuit de charge.', objectif:'Mesurer tension de charge et chutes de tension.', materiel:['Multimètre','Pince ampèremétrique','Schéma'], etudePrelim:[{q:'13,8–14,4 V: pourquoi cette plage ?',r:''},{q:'Effet courroie détendue ?',r:''},{q:'Rôle régulateur ?',r:''}], activitePratique:[ etape('Mesures','35 min',['Repos/ralenti/2000 tr/min.','Consommateurs ON.','Chutes +B/masse.']), etape('Inspection','30 min',['Courroie/galets.','Oxydation bornes.','Bruit alternateur.']), etape('Conclusion','20 min',['Connexions/courroie/alternateur.','Actions.']) ], securiteRangement:['Éviter pièces en rotation','Batterie off si dépose','Tracer'], pointsCles:['Tension OK','Connexions propres','Tension courroie'] },
  6:{ id: 6, duree:'2h00', titre:'UE 206 • Contrôle de l\'alternateur', situation:'Contrôle détaillé alternateur (composants).', objectif:'Tester rotor/stator/diodes/régulateur.', materiel:['Banc alternateur','Multimètre','Diodes','Régulateur'], etudePrelim:[{q:'Composants alternateur ?',r:''},{q:'Test pont de diodes ?',r:''},{q:'Limite régulation tension ?',r:''}], activitePratique:[ etape('Dépose','25 min',['Batterie off, détendre courroie.','Déconnexion/vis.','Extraction.']), etape('Contrôles','45 min',['Rotor 3–5 Ω.','Stator 0,1–0,3 Ω.','Pont de diodes sens unique.','Régulateur.']), etape('Banc','35 min',['Tension 14 V.','Intensité nominale.','Stabilité sans survoltage.']), etape('Repose','15 min',['Couples/tension courroie.','Test charge véhicule.']) ], securiteRangement:['Batterie off','Ranger banc','Nettoyage'], pointsCles:['Diodes OK','Régulation <14,8 V','Test banc'] },
  7:{ id: 7, duree:'2h00', titre:'CA 209 • Fermeture centralisée', situation:'Diagnostic fermeture centralisée.', objectif:'Tester moteurs/commande/appairage télécommande.', materiel:['Valise diag','Multimètre','Télécommande','Pile CR2032'], etudePrelim:[{q:'Principe fermeture centralisée ?',r:''},{q:'Mécanique vs électrique ?',r:''},{q:'Procédure d’appairage ?',r:''}], activitePratique:[ etape('Diag','25 min',['Tests clé/télécommande.','Codes défauts.','Pile 3 V.']), etape('Actionneurs','50 min',['Alim moteurs 12 V +/-.','Microrupteurs.','Faisceaux.']), etape('Télécommande','30 min',['Émission IR/Radio.','Appairage.','Validation.']) ], securiteRangement:['Ranger garnitures','Clips intacts','Tracer'], pointsCles:['Pile d’abord','Moteur ou méca','Appairage'] },
  8:{ id: 8, duree:'2h00', titre:'UE 211 • Diagnostic d\'un circuit électrique (feux stop)', situation:'Feux stop inopérants: méthode.', objectif:'Isoler la panne et corriger.', materiel:['Schéma','Multimètre','Fusibles','Ampoules'], etudePrelim:[{q:'Chemin +12 V jusqu’aux feux ?',r:''},{q:'Contacteur de stop: test ?',r:''},{q:'Point-milieu ?',r:''}], activitePratique:[ etape('Simples','25 min',['Ampoules/fusibles.','Connecteurs/masse.','Contacteur.']), etape('Ciblées','45 min',['Entrée/sortie contacteur.','Continuité vers feux.','Chute de tension masse.']), etape('Validation','20 min',['Réparation.','Recontrôle.']) ], securiteRangement:['Couper contact','Respect sections/fusibles','Fixation faisceaux'], pointsCles:['Schéma','Point-milieu','Mesures'] },
  9:{ id: 9, duree:'1h45', titre:'UE 210 • Câblage des clignotants', situation:'Câblage clignotants (maquette/véhicule).', objectif:'Câbler conforme et valider fréquence.', materiel:['Centrale','Commodo','Ampoules 21 W','Câbles/cosses'], etudePrelim:[{q:'Centrale thermique/électronique ?',r:''},{q:'Fréquence nominale ?',r:''},{q:'Effet ampoule grillée ?',r:''}], activitePratique:[ etape('Maquette','40 min',['Alim centrale.','Commodo G/D.','Ampoules AV/AR.']), etape('Tests','40 min',['Fonctionnement G/D.','Warning.','Fréquence OK.']), etape('Véhicule','25 min',['Identifier centrale.','Contrôler relais/ampoules.','Tracer.']) ], securiteRangement:['Débrancher maquette','Ranger câbles','Archiver schéma'], pointsCles:['Centrale clé','Warning = test global','Fréquence'] },
  10:{ id: 10, duree:'2h00', titre:'UE 205 • Câblage d\'un circuit de moto-ventilateur', situation:'Câblage moto-ventilateur PV/GV (relais/résistance).', objectif:'Réaliser montage et valider déclenchements.', materiel:['Relais double','Résistance PV','Sonde T°','Fusibles 40 A'], etudePrelim:[{q:'PV vs GV: principe ?',r:''},{q:'Rôle résistance série ?',r:''},{q:'Commande thermo/calculateur ?',r:''}], activitePratique:[ etape('Câblage','50 min',['Alim + batt via fusible.','Relais PV/GV.','Résistance PV → moto.']), etape('Tests','45 min',['PV: intensité ~10 A.','GV: ~25 A.','Déclenchement thermique/diag.']), etape('Véhicule','25 min',['Identifier relais/R.','Vérifier déclenchements.']) ], securiteRangement:['Débrancher maquette','Fixer câbles','Tracer'], pointsCles:['Résistance = PV','Intensités distinctes','Relais OK'] },
  11:{ id: 11, duree:'1h45', titre:'ME 205 • Contrôle circuit moto-ventilation refroidissement', situation:'Contrôle moto-ventilation sur véhicule.', objectif:'Valider PV/GV et températures de déclenchement.', materiel:['Valise','Multimètre','Thermo IR','Schéma'], etudePrelim:[{q:'Températures PV/GV typiques ?',r:''},{q:'Conséquences défaut moto-ventilateur ?',r:''},{q:'Commande via ECU/sonde ?',r:''}], activitePratique:[ etape('Fonctionnel','35 min',['Montée T° moteur.','PV puis GV.','Temps refroidissement.']), etape('Électrique','40 min',['Alim relais 12 V.','Intensités PV/GV.','Masse <0,3 V chute.']), etape('Diag','30 min',['Codes ECU.','Forcer PV/GV.','Préconisations.']) ], securiteRangement:['Laisser refroidir','Débrancher valise','Tracer'], pointsCles:['PV→GV','Intensités cohérentes','Températures'] },
  12:{ id: 12, duree:'2h00', titre:'CA 210 • Vitres électriques', situation:'Diagnostic lève-vitres électriques.', objectif:'Discriminer panne moteur/mécanique/commande.', materiel:['Multimètre','Graisse silicone','Dégraffeur','Schéma'], etudePrelim:[{q:'Principe lève-vitre et anti-pincement ?',r:''},{q:'Initialisation après coupure batterie ?',r:''},{q:'Symptômes moteur HS vs mécanique ?',r:''}], activitePratique:[ etape('Diag','25 min',['Commandes conducteur/passager.','Fusible lève-vitres.','Verrou enfant.']), etape('Électrique','45 min',['Alim moteur 12 V +/-.','Résistance ~5–15 Ω.','Inverseur continuité.']), etape('Mécanique','35 min',['Rails/câbles.','Graissage.','Butées.']), etape('Init','15 min',['Cycles complets.','Test anti-pincement.']) ], securiteRangement:['Clips intacts','Propreté vitres','Tracer'], pointsCles:['Moteur vs méca','Initialisation','Graissage'] },
  13:{ id: 13, duree:'1h45', titre:'CA 208 • Diagnostic essuie-vitre', situation:'Diagnostic essuie-vitre et lave-glace.', objectif:'Identifier défaut (moteur/relais/commodo/parking).', materiel:['Multimètre','Relais test','Fusibles','Schéma'], etudePrelim:[{q:'PV/GV/intermittent: principe ?',r:''},{q:'Fin de course (parking) ?',r:''},{q:'Commande intermittent: relais ou ECU ?',r:''}], activitePratique:[ etape('Diag','25 min',['Positions commodo.','Fusible.','Lave-glace.']), etape('Électrique','50 min',['Alim moteur.','Commodo continuité.','Relais intermittent.','Contacteur parking.']), etape('Mécanique','25 min',['Biellette/axes.','Ressort bras.','Pompe lave-glace.']) ], securiteRangement:['Couper contact','Ranger caches','Tracer'], pointsCles:['Commodo','Relais','Parking'] },
  14:{ id: 14, duree:'3h00', titre:'MTE 203 • Remplacement distribution et pompe à eau', situation:'Remplacement distribution + pompe à eau.', objectif:'Procédure constructeur, calage parfait.', materiel:['Kit distri','Piges','Clé dynamo','LR'], etudePrelim:[{q:'Pourquoi ne pas tourner vilo seul DOHC ?',r:''},{q:'Repères PMH/AAC ?',r:''},{q:'Couples critiques ?',r:''}], activitePratique:[ etape('Calage','35 min',['Dépose protections.','Repères/sens courroie.','Piges vilo/AAC.']), etape('Remplacement','90 min',['Pompe/galets neufs.','Pose/tension courroie.','2 tours et recontrôle.']), etape('Finition','35 min',['Remplir/purger.','Contrôle fuites/bruits.','Traçabilité.']) ], securiteRangement:['Batterie off','Couples stricts','Plans propres'], pointsCles:['Calage exact','Tension','Purge'] },
  15:{ id: 15, duree:'2h00', titre:'MTE 208 • Relevé compression / fuite', situation:'Compression et test de fuite (essence/diesel).', objectif:'Identifier cylindre faible et localiser la fuite.', materiel:['Compressiomètre','Test fuite (air 6–8 bar)','Clés','Huile'], etudePrelim:[{q:'Valeurs compressions essence/diesel ?',r:''},{q:'Écart maxi entre cylindres (%) ?',r:''},{q:'Interprétation test fuite (où sort l’air) ?',r:''}], activitePratique:[ etape('Préparation','25 min',['Moteur chaud.','Dépose bougies/injecteurs.','Couper allumage/injection.']), etape('Compression','50 min',['Démarreur 5–7 tours.','Relever chaque cylindre.','Test à l’huile si faible.']), etape('Fuite','40 min',['PMH compression cylindre faible.','Air 6 bar, % fuite.','Écoute: admission/échappement/reniflard/radiateur.']) ], securiteRangement:['Batterie off si dépose','Couple bougies','Tracer'], pointsCles:['Écart <10%','Seg/Soup/JDC','PMH exact'] },
  16:{ id: 16, duree:'2h00', titre:'AS 209 • Pré-contrôle technique', situation:'Pré-contrôle CT priorité sécurité.', objectif:'Préparer le véhicule à la visite.', materiel:['Check-list CT','OBD','Luxmètre','Mano pneus'], etudePrelim:[{q:'Rubriques CT ?',r:''},{q:'Minima pneus/freins ?',r:''},{q:'DTC permanents = contre-visite ?',r:''}], activitePratique:[ etape('Visuels','35 min',['Éclairage, vitrages, corrosion.','Pneus, fuites visibles, échappement.']), etape('Mesures','35 min',['Réglage phares.','Pressions pneus.','Lecture OBD.']), etape('Restitution','20 min',['Défaillances/gravité.','Préconisations.']) ], securiteRangement:['Consignes atelier','Ranger outils','Archiver fiche'], pointsCles:['Réglementaire','OBD clean','Traçabilité'] },
  17:{ id: 17, duree:'2h00', titre:'MTE 210 • Pression d\'huile (circuit de lubrification)', situation:'Pression d’huile et circuit de lubrification.', objectif:'Mesurer pression ralenti/3000 tr/min et diagnostiquer.', materiel:['Mano 0–10 bar','Adaptateur capteur','Multimètre','RTA'], etudePrelim:[{q:'Pression ralenti/3000 typiques ?',r:''},{q:'Rôle clapet limiteur ?',r:''},{q:'Symptômes pression faible ?',r:''}], activitePratique:[ etape('Installation','30 min',['Moteur chaud.','Dépose capteur, pose mano.','Vérif niveau/viscosité.']), etape('Mesures','50 min',['Ralenti (1–2 bar).','3000 tr/min (3–6 bar).','Stabilité.']), etape('Diag','30 min',['Filtre/huile/pompe/clapet/coussinets.','Codes ECU si présents.']) ], securiteRangement:['Huile chaude','Nettoyage fuites','Tracer'], pointsCles:['Pression cible','Stabilité','Causes'] },
  18:{ id: 18, duree:'2h00', titre:'MA 201 • Contrôle pression et débit essence', situation:'Pression/débit essence.', objectif:'Vérifier régulation et débit pompe.', materiel:['Mano 0–6 bar','Éprouvette','RTA'], etudePrelim:[{q:'Pression rampe cible ?',r:''},{q:'Maintien pression (clapet) ?',r:''},{q:'Débit minimal (L/min) ?',r:''}], activitePratique:[ etape('Pression','40 min',['Contact ON: montée.','Ralenti/accélération.','Maintien moteur OFF.']), etape('Débit','40 min',['Mesure 30 s.','Extrapolation L/min.','Comparaison RTA.']) ], securiteRangement:['Ventilation/anti-incendie','Éliminer essence','Tracer'], pointsCles:['Pression','Débit','Maintien'] },
  19:{ id: 19, duree:'2h00', titre:'MA 208 • Contrôle des injecteurs moteur diesel classique', situation:'Injecteurs diesel classiques: ouverture/pulvérisation.', objectif:'Tester au banc et conclure.', materiel:['Banc injecteurs','Gasoil propre','Éprouvettes'], etudePrelim:[{q:'Pression d’ouverture typique ?',r:''},{q:'Critères pulvérisation ?',r:''},{q:'Signes injecteur HS ?',r:''}], activitePratique:[ etape('Dépose','30 min',['Nettoyage zones.','Dépose lignes/retours.','Extraction (joints cuivre).']), etape('Banc','60 min',['Pression d’ouverture.','Cône homogène.','Étanchéité nez.']), etape('Repose','30 min',['Joints neufs.','Couple injecteur.','Purge HP/démarrage.']) ], securiteRangement:['Protection œil','Déchets gasoil','Tracer pressions'], pointsCles:['Pression','Pulvérisation','Étanchéité'] },
  20:{ id: 20, duree:'2h30', titre:'F 204 • Remplacement maître-cylindre', situation:'Remplacement maître-cylindre.', objectif:'Reposer et purger correctement.', materiel:['Maître-cylindre','DOT 4','Purgeur','Clés'], etudePrelim:[{q:'Rôle maître-cylindre (tandem) ?',r:''},{q:'Symptômes fuite interne/externe ?',r:''},{q:'Procédure purge ?',r:''}], activitePratique:[ etape('Dépose','40 min',['Aspirer LDF réservoir.','Débrancher sorties/fixation.','Extraction.']), etape('Repose/purge','60 min',['Préremplir.','Raccorder sorties.','Purge ARD→ARG→AVD→AVG.']), etape('Validation','10 min',['Pédale ferme.','Absence fuites.']) ], securiteRangement:['LDF corrosif','Nettoyage immédiat','Élimination LDF'], pointsCles:['Purge complète','Niveau réservoir','Pédale dure'] },
  21:{ id: 21, duree:'1h45', titre:'F 206 • Relevé de pressions de freinage', situation:'Pressions freinage aux 4 roues.', objectif:'Détecter déséquilibres et localiser la cause.', materiel:['4 manomètres','Adaptateurs','Assistant'], etudePrelim:[{q:'Pressions AV/AR typiques ?',r:''},{q:'Rôle répartiteur ?',r:''},{q:'Écart G/D admissible ?',r:''}], activitePratique:[ etape('Installation','30 min',['T sur durites/vis purge.','Repérage roues.']), etape('Mesures','45 min',['Mi-course et max.','Comparer AV/AR et G/D.','Conclusions.']) ], securiteRangement:['Dépose mano','Purge si air','Tracer'], pointsCles:['Symétrie','AR<AV','Répartiteur'] },
  22:{ id: 22, duree:'2h00', titre:'F 208 • Diagnostic du circuit de freinage avec passage au banc', situation:'Freinage au banc rouleaux.', objectif:'Mesurer efficacité/équilibre/frein à main.', materiel:['Banc rouleaux','Fiche résultats'], etudePrelim:[{q:'Efficacité mini (%) ?',r:''},{q:'Déséquilibre max (%) ?',r:''},{q:'Frein à main mini (%) ?',r:''}], activitePratique:[ etape('Préparation','20 min',['Pressions pneus.','Inspection rapide.','Consignes.']), etape('AV','30 min',['Mesure forces AVD/AVG.','Déséquilibre.']), etape('AR','30 min',['Mesure ARD/ARG.','Frein à main.']), etape('Interprétation','20 min',['>50% total, <30% déséquilibre, frein à main >16%.']) ], securiteRangement:['Descendre du banc','Ranger','Tracer'], pointsCles:['Efficacité','Équilibre','Frein à main'] },
  23:{ id: 23, duree:'2h00', titre:'F 209 • Diagnostic assistance au freinage', situation:'Assistance au freinage (servo dépression ou système hydraulique).', objectif:'Tester l’assistance, vérifier dépression/pression et composants associés.', materiel:['Vacuomètre', 'Manomètre pression', 'Valise (si hydraulique)', 'Schéma'], etudePrelim:[{ q: 'Principe servofrein à dépression ?', r: '' },{ q: 'Dépression normale (mbar/inHg) ?', r: '' },{ q: 'Symptômes d’une assistance défaillante ?', r: '' }], activitePratique:[etape('Test fonctionnel', '30 min', ['Pomper moteur OFF, maintenir pédale, démarrer.','Pédale s’enfonce légèrement = assistance OK.','Test maintien dépression moteur coupé.']),etape('Mesure dépression', '40 min', ['Vacuomètre sur durite (collecteur/pompe ↔ servofrein).','Mesurer au ralenti (≈ 500–700 mbar).','Contrôler clapet anti-retour et fuites durites.']),etape('Hydraulique (si équipé)', '35 min', ['Lire défauts via valise.','Mesurer pression accumulateur.','Tester capteur de pression et contacteur pédale.'])], securiteRangement:['Raccorder durites correctement', 'Ranger instruments', 'Tracer mesures'], pointsCles:['Pédale plus souple moteur ON', 'Dépression suffisante', 'Clapet étanche'] },
  24:{ id: 24, duree:'4h00', titre:'T 201 • Dépose-pose embrayage', situation:'Dépose-pose embrayage (disque/mécanisme/butée).', objectif:'Remplacer le kit et valider un débrayage correct.', materiel:['Kit embrayage', 'Centreur', 'Cric boîte', 'Clé dynamo'], etudePrelim:[{ q: 'Symptômes (patinage, broutage, point de touche) ?', r: '' },{ q: 'Importance du centrage disque ?', r: '' },{ q: 'Couples serrage et huile BV ?', r: '' }], activitePratique:[etape('Dépose BV', '80 min', ['Lever et sécuriser le véhicule.','Dépose cardans/supports/connexions.','Extraction BV au cric.']),etape('Remplacement', '50 min', ['Butée neuve et guidage.','Centrer disque avec outil.','Serrer mécanisme au couple.']),etape('Repose/validation', '80 min', ['Reposer BV/supports/cardans.','Commande/purge si hydraulique.','Essai route: point de touche et patinage.'])], securiteRangement:['Sécurité levage', 'Couples respectés', 'Ranger l’outillage'], pointsCles:['Centrage parfait', 'Commande correcte', 'Essai validé'] },
  25:{ id: 25, duree:'2h30', titre:'T 208 • Remplacement commande d\'embrayage hydraulique', situation:'Commande hydraulique d’embrayage (émetteur/récepteur).', objectif:'Remplacer l’organe défectueux et purger correctement.', materiel:['Émetteur ou récepteur', 'DOT 4', 'Purgeur', 'Clés'], etudePrelim:[{ q: 'Principe de la commande hydraulique ?', r: '' },{ q: 'Symptômes (pédale molle/dure, fuite) ?', r: '' },{ q: 'Procédure de purge (ordre/points) ?', r: '' }], activitePratique:[etape('Dépose', '40 min', ['Aspirer le LDF du bocal.','Débrancher durites/fixations.','Extraire émetteur/récepteur.']),etape('Repose/purge', '60 min', ['Monter l’organe neuf.','Remplir DOT 4.','Purger jusqu’à disparition des bulles.']),etape('Validation', '10 min', ['Course pédale normale.','Passage des vitesses à l’arrêt.','Traçabilité.'])], securiteRangement:['LDF corrosif', 'Nettoyage immédiat', 'Élimination déchets'], pointsCles:['Purge complète', 'Aucune fuite', 'Course validée'] },
  26:{ id: 26, duree:'3h00', titre:'T 206 • Découverte de la boîte de vitesses', situation:'Découverte d’une BV mécanique: démontage partiel et analyse.', objectif:'Identifier pignons, synchros, arbres et fourchettes.', materiel:['BV didactique', 'Extracteurs', 'Bac nettoyage', 'Schéma BV'], etudePrelim:[{ q: 'Rôle d’une boîte de vitesses ?', r: '' },{ q: 'Fonction synchroniseur ?', r: '' },{ q: 'Constitution arbres/pignons ?', r: '' }], activitePratique:[etape('Ouverture', '50 min', ['Vidanger la BV.','Ouvrir le carter.','Repérer les ensembles.']),etape('Analyse', '80 min', ['Usure synchros/crabots.','Jeux roulements.','Sélection et fourchettes.']),etape('Remontage', '70 min', ['Joints/circlips neufs.','Graissage adapté.','Contrôle de rotation et passages.'])], securiteRangement:['Recycler l’huile', 'Nettoyer pièces', 'Ranger outils'], pointsCles:['Méthode', 'Repères', 'Jeux maîtrisés'] },
  27:{ id: 27, duree:'3h30', titre:'T 205 • Échange synchro 5e', situation:'Échange synchroniseur de 5e.', objectif:'Supprimer craquements et valider l’engagement.', materiel:['Synchro 5e', 'Extracteurs', 'Circlips neufs', 'Huile BV'], etudePrelim:[{ q: 'Pourquoi la 5e est souvent sollicitée ?', r: '' },{ q: 'Signes synchro HS ?', r: '' },{ q: 'Jeux admissibles ?', r: '' }], activitePratique:[etape('Accès', '80 min', ['Déposer la BV du véhicule.','Accéder au carter 5e.','Bloquer l’arbre pour desserrage.']),etape('Remplacement', '60 min', ['Extraire baladeur.','Monter bagues/ressorts.','Contrôle jeux au comparateur.']),etape('Validation', '60 min', ['Remontage + huile.','Essai route 4⇄5.','Traçabilité.'])], securiteRangement:['Recycler huile', 'Couples respectés', 'Archiver photos'], pointsCles:['Jeux OK', 'Passage doux', 'Pas de craquement'] },
  28:{ id: 28, duree:'1h30', titre:'L 204 • Effectuer un pré-contrôle géométrie', situation:'Pré-contrôle géométrie: jeux/états/pressions.', objectif:'Valider la préparation avant banc 3D.', materiel:['Pont', 'Mano pneus', 'Jauge profondeur', 'Lampe'], etudePrelim:[{ q: 'Pourquoi régler pression avant mesure ?', r: '' },{ q: 'Quels jeux contrôler ?', r: '' },{ q: 'Impact d’un jeu sur la mesure ?', r: '' }], activitePratique:[etape('Pneus', '20 min', ['Pressions/sculptures.','Usures irrégulières.']),etape('Train AV', '35 min', ['Rotules/silentblocs.','Roulements/amortisseurs.']),etape('Train AR', '25 min', ['Bras/biellettes.','Fixations.'])], securiteRangement:['Descendre du pont', 'Ranger outils', 'Fiche remplie'], pointsCles:['Pressions', 'Aucun jeu', 'Prêt banc'] },
  29:{ id: 29, duree:'2h00', titre:'L 207 • Contrôler géométrie. Régler le parallélisme', situation:'Géométrie sur banc et réglage parallélisme.', objectif:'Obtenir des valeurs dans tolérances avec volant centré.', materiel:['Banc 3D', 'Clés biellettes', 'Fiches constructeur'], etudePrelim:[{ q: 'Définir parallélisme/carrossage/chasse ?', r: '' },{ q: 'Conséquences mauvais parallélisme ?', r: '' },{ q: 'Charge/pressions: pourquoi cruciales ?', r: '' }], activitePratique:[etape('Mesures', '50 min', ['Compensation jantes.','Lecture AV/AR.','Identifier hors tolérances.']),etape('Réglages', '40 min', ['Biellettes AV (AR si possible).','Itérer jusqu’au vert.','Centrer le volant.']),etape('Validation', '10 min', ['Imprimer fiches.','Essai court.'])], securiteRangement:['Serrer contre-écrous', 'Ranger capteurs', 'Archiver'], pointsCles:['Symétrie', 'Itératif', 'Volant centré'] },
  30:{ id: 30, duree:'2h30', titre:'L 213 • Découverte et entretien suspension hydraulique', situation:'Suspension hydraulique/hydropneumatique.', objectif:'Contrôler assiette, pressions sphères, purger circuit.', materiel:['Mano HP', 'Station azote', 'LHM/fluide', 'Valise'], etudePrelim:[{ q: 'Sphère azote/LHM: principe ?', r: '' },{ q: 'Pressions typiques AV/AR ?', r: '' },{ q: 'Rôle régulateur hauteur/pompe HP ?', r: '' }], activitePratique:[etape('Assiette/diag', '40 min', ['Hauteurs 4 coins.','Comparaison tolérances.','Codes défauts.']),etape('Pressions', '50 min', ['Décharger circuit.','Mesurer/regonfler azote.','Remplacer sphère si membrane HS.']),etape('Purge/validation', '50 min', ['Compléter LHM.','Purger et manœuvrer hauteurs.','Essai et traçabilité.'])], securiteRangement:['Azote uniquement', 'Protection yeux', 'Éliminer LHM'], pointsCles:['Pression=confort', 'Assiette', 'Purge'] },
  31:{ id: 31, duree:'1h45', titre:'MTE 202 • Contrôle étanchéité circuit de refroidissement', situation:'Étanchéité circuit refroidissement.', objectif:'Pressuriser, traquer fuites, conclure.', materiel:['Pompe test + mano', 'Adaptateur bouchon', 'Traceur UV'], etudePrelim:[{ q: 'Pression circuit à chaud ?', r: '' },{ q: 'Signes joint de culasse ?', r: '' },{ q: 'Fonction bouchon taré ?', r: '' }], activitePratique:[etape('Test pression', '50 min', ['Moteur froid, 1,2–1,6 bar.','Observer chute et points humides.','UV si nécessaire.']),etape('Compléments', '30 min', ['Gaz dans LR (kit).','Huile émulsionnée ?']),etape('Conclusion', '10 min', ['Fuite localisée.','Re-test après réparation.'])], securiteRangement:['Moteur froid', 'Relâcher pression', 'Tracer'], pointsCles:['Pression tient', 'UV utile', 'JDC si gaz'] },
  32:{ id: 32, duree:'2h00', titre:'MA 202 • Diagnostic (prise en main matériel). Lecture paramètres', situation:'Valise diag: DTC, freeze, PIDs.', objectif:'Lire/interpréter, effacer et revalider.', materiel:['Valise', 'Chargeur maintien', 'Adaptateurs'], etudePrelim:[{ q: 'DTC vs freeze vs PID ?', r: '' },{ q: 'PIDs clés ?', r: '' },{ q: 'Précautions alim ?', r: '' }], activitePratique:[etape('Connexion', '25 min', ['OBD, identification ECU.','Lire/enregistrer DTC.','Effacement contrôlé.']),etape('PIDs', '40 min', ['Sélection pertinente.','Ralenti/charge.','Comparer RTA.']),etape('Validation', '15 min', ['Essai conditions défaut.','Relecture DTC.'])], securiteRangement:['Maintien charge', 'Déconnexion propre', 'Archiver logs'], pointsCles:['DTC lus', 'PIDs pertinents', 'Validation'] },
  33:{ id: 33, duree:'2h00', titre:'MA 210 • Identification structurelle du système d\'injection', situation:'Identification structurelle injection.', objectif:'Localiser capteurs/actionneurs et flux air/carburant.', materiel:['Schémas', 'Photos', 'Étiquettes', 'RTA'], etudePrelim:[{ q: 'Essence (mono/multipoint/directe) ?', r: '' },{ q: 'Diesel (ID/CR/IP) ?', r: '' },{ q: 'Boucles régulation (lambda/EGR/turbo) ?', r: '' }], activitePratique:[etape('Essence', '50 min', ['ECU/rampe/injecteurs.','MAF/MAP, lambda.','Papillon/allumage.']),etape('Diesel', '50 min', ['Pompe HP/rail.','Injecteurs, PMH/AAC.','EGR, FAP (ΔP).'])], securiteRangement:['Ne pas débrancher moteur tournant', 'Protéger connecteurs', 'Archiver'], pointsCles:['Cartographie', 'Noms exacts', 'Flux'] },
  34:{ id: 34, duree:'2h30', titre:'MA 204 • Diagnostic système injection essence', situation:'Diagnostic injection essence.', objectif:'Lier DTC/PIDs à des tests capteurs/actionneurs.', materiel:['Valise', 'Multimètre', 'Oscillo', 'Mano essence'], etudePrelim:[{ q: 'Symptômes injection ?', r: '' },{ q: 'Pression rampe ?', r: '' },{ q: 'Lambda attendue ?', r: '' }], activitePratique:[etape('Lecture', '30 min', ['DTC + freeze.','PIDs MAF/MAP/λ/FRP.','Effacement/test.']),etape('Capteurs', '60 min', ['MAF tension.','MAP vs dépression.','Lambda amont/aval.','PMH/AAC oscillo.']),etape('Actionneurs', '40 min', ['Injecteurs (Ω/signal).','Papillon/EGR.','Régulateur pression.'])], securiteRangement:['Déconnexions propres', 'Ranger appareils', 'Tracer'], pointsCles:['DTC+PIDs', 'Capteurs confirment', 'Actionneurs valident'] },
  35:{ id: 35, duree:'2h00', titre:'ME 202 • Contrôle du circuit d\'allumage', situation:'Circuit d’allumage: bobines/bougies/câbles.', objectif:'Diagnostiquer ratés et valider étincelle.', materiel:['Multimètre', 'Oscillo', 'Clé bougie', 'Testeur étincelle'], etudePrelim:[{ q: 'Types allumage (DIS/bobine crayon) ?', r: '' },{ q: 'Tension secondaire (kV) ?', r: '' },{ q: 'Signes défaut allumage ?', r: '' }], activitePratique:[etape('Pré-diagnostic', '20 min', ['DTC P030x.','Inspection bougies/bobines.','Ralenti (ratés).']),etape('Bobines', '45 min', ['Ω primaire/secondaire.','Isolement.','Signal primaire oscillo.','Test étincelle.']),etape('Bougies', '40 min', ['Électrodes/écartement.','Couleur (richesse).','Remplacement au couple.'])], securiteRangement:['HT prudence', 'Couples bougies', 'Tracer'], pointsCles:['Bobine OK', 'Bougie OK', 'Courbes oscillo'] },
  36:{ id: 36, duree:'1h45', titre:'ME 203 • Contrôle du circuit de pré-post chauffage', situation:'Pré/post-chauffage diesel.', objectif:'Tester bougies, relais et temporisation.', materiel:['Multimètre', 'Pince ampèremétrique', 'Chrono', 'Schéma'], etudePrelim:[{ q: 'Rôle préchauffage ?', r: '' },{ q: 'Intensité par bougie ?', r: '' },{ q: 'Durée temporisation vs T° ?', r: '' }], activitePratique:[etape('Circuit', '35 min', ['Voyant TDB/temps.','Tension barre.','Intensité totale.']),etape('Bougies', '45 min', ['Ω par bougie.','Intensité individuelle.','Inspection extrémité.']),etape('Relais/boîtier', '20 min', ['Activation/commande.','Post-chauffage.'])], securiteRangement:['Batterie off si dépose', 'Couples', 'Tracer'], pointsCles:['Homogène', 'Commande OK', 'Temps conforme'] },
  37:{ id: 37, duree:'2h00', titre:'MP 201 • Analyser les gaz d\'échappement essence et diesel', situation:'Analyse gaz échappement essence/diesel.', objectif:'Comparer aux normes et cibler l’organe défaillant.', materiel:['Analyseur 4/5 gaz', 'Opacimètre', 'Thermo IR', 'RTA'], etudePrelim:[{ q: 'Repères CO/HC/λ essence ?', r: '' },{ q: 'Opacité diesel: seuils ?', r: '' },{ q: 'NOx élevé: causes ?', r: '' }], activitePratique:[etape('Essence', '50 min', ['Moteur chaud.','Ralenti + 2500 tr/min.','CO/HC/O2/CO2/λ.']),etape('Diesel', '50 min', ['Opacimètre (3 accélérations).','K ou % opacité.','Interpréter graphiques.'])], securiteRangement:['Ventilation', 'Sondes propres', 'Archiver résultats'], pointsCles:['CO/HC/λ', 'Opacité', 'Organe ciblé'] },
  38:{ id: 38, duree:'1h30', titre:'MP 202 • Contrôle des sondes lambda', situation:'Contrôle sondes lambda amont/aval.', objectif:'Vérifier oscillations et temps de réponse.', materiel:['Valise', 'Oscillo', 'Multimètre', 'Clé sonde'], etudePrelim:[{ q: 'Rôle amont vs aval ?', r: '' },{ q: 'Oscillations 0,1–0,9 V ~1 Hz ?', r: '' },{ q: 'Sonde lente: indices ?', r: '' }], activitePratique:[etape('Lecture diag', '25 min', ['PIDs lambda amont/aval.','Boucle fermée chaude.','Tests enrichir/appauvrir.']),etape('Mesures', '35 min', ['Oscillo amont (pentes nettes).','Réchauffeur (Ω/12 V).','Aval stable si catalyseur OK.']),etape('Diagnostic', '25 min', ['Amont lente = remplacement.','Aval oscillante = catalyseur HS.'])], securiteRangement:['Prudence échappement', 'Couple serrage', 'Tracer'], pointsCles:['Amont oscille', 'Aval contrôle cat', 'Temps réponse'] }
});

