
export type Etape = {
  titre: string;
  duree: string;
  etapes: string[];
};

export type EtudePrelimText = {
  type: 'text';
  q: string;
  r: string; // Correct answer
};

export type EtudePrelimQCM = {
  type: 'qcm';
  q: string;
  options: string[];
  r: string; // Correct answer
};

export type EtudePrelim = EtudePrelimText | EtudePrelimQCM;


export type TP = {
  id: number;
  duree: string;
  titre: string;
  situation: string;
  objectif: string;
  materiel: string[];
  etudePrelim: EtudePrelim[];
  activitePratique: Etape[];
  securiteRangement: string[];
  pointsCles: string[];
};

function etape(titre: string, duree: string, etapes: string[]): Etape {
    return { titre, duree, etapes };
}

export const tpPremiere: Record<number, TP> = {
  1:{ id: 1, duree:'2h00', titre:'AS 207 • Accueillir le client et restituer le véhicule', situation:'Un client se présente à l\'atelier sans rendez-vous. Son véhicule est immobilisé. Vous êtes chargé de l\'accueillir, de prendre en charge le véhicule en créant un Ordre de Réparation (OR) complet et de lui expliquer la procédure à suivre.', objectif:'Réaliser un accueil et une restitution professionnels, avec OR et traçabilité. (Compétence C2.1)', materiel:['OR','Grille d’état','Tablette atelier','Documents garantie'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de scénario : Un client arrive, sa voiture ne démarre plus. Il n'a pas de rendez-vous et semble pressé. Quelle est votre première action pour le rassurer tout en respectant la procédure de l'atelier ?",r:'Écouter activement, montrer de l\'empathie, puis expliquer les étapes à venir (prise en charge, diagnostic initial).'},
        {type: 'text', q:"L'OR est un contrat. Citez les 3 informations les plus critiques à y faire figurer pour protéger à la fois le client et l'atelier. Justifiez vos choix.",r:'1. Identité client/véhicule (immat, km). 2. Demande claire du client (symptôme). 3. Date et signature pour accord. Cela évite les litiges.'},
        {type: 'qcm', q:"Le client vous dit : 'Le problème est apparu juste après votre dernière intervention, ça doit être sous garantie !'. Comment réagissez-vous ?", options: ["Je confirme que c'est sous garantie pour le calmer.", "Je lui dis que ce n'est pas possible.", "Je reste factuel, vérifie l'historique et lui explique que nous allons diagnostiquer la cause avant de parler de garantie."], r:"Je reste factuel, vérifie l'historique et lui explique que nous allons diagnostiquer la cause avant de parler de garantie."}
    ], 
    activitePratique:[ etape('Accueil et Prise en Charge','30 min',['Accueillir le client avec professionnalisme et courtoisie.','Écouter activement les symptômes décrits par le client.','Effectuer une inspection visuelle du véhicule en présence du client.','Rédiger un Ordre de Réparation (OR) complet incluant immatriculation, kilométrage et demande précise.']), etape('Suivi de l\'Intervention','30 min',['Informer le client des délais prévisionnels.','Obtenir un accord écrit pour les travaux complémentaires.']), etape('Restitution du Véhicule','40 min',['Expliquer clairement la facture au client.','Donner des conseils d\'entretien et planifier le prochain rendez-vous.','Archiver le dossier et s\'assurer de la satisfaction du client.']) ], securiteRangement:['Protection des données personnelles (RGPD)','Archivage méthodique des OR','Maintien d\'un espace d\'accueil propre et ordonné'], pointsCles:['Clarté de l\'OR','Traçabilité des interventions','Posture professionnelle'] },
  2:{ id: 2, duree:'1h30', titre:'UE 203 • Utilisation d\'un multimètre', situation:'Un véhicule présente des dysfonctionnements électriques intermittents. Avant tout diagnostic, le chef d\'atelier vous demande de valider votre maîtrise du multimètre sur une maquette puis sur le véhicule.', objectif:'Mesurer tension, résistance et continuité correctement et en sécurité pour préparer un diagnostic. (Compétence C2.1)', materiel:['Multimètre','Pointes de touche','Fusibles de test','Schéma électrique simple'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de risque : Vous devez mesurer l'intensité du courant consommé par le démarreur. Pourquoi est-ce une opération risquée avec un multimètre standard et quel outil faut-il utiliser à la place ?",r:'Un multimètre standard est limité à 10A ou 20A, or un démarreur consomme plus de 150A. Cela ferait griller le fusible interne du multimètre. Il faut utiliser une pince ampèremétrique.'},
        {type: 'qcm', q:"Vous mesurez 0V aux bornes d'un consommateur qui devrait fonctionner. Quelle est la cause la plus probable ?", options: ["Le consommateur est en court-circuit.", "Le circuit est ouvert en amont (câble coupé, fusible HS).", "La batterie est trop chargée."], r:"Le circuit est ouvert en amont (câble coupé, fusible HS)."},
        {type: 'text', q:"Réflexion : Pourquoi doit-on impérativement couper l'alimentation du circuit avant de mesurer une résistance (Ω) ?",r:'Parce que le multimètre injecte son propre petit courant pour mesurer la résistance. La présence d\'une tension extérieure fausserait la mesure et pourrait endommager l\'appareil.'}
    ], 
    activitePratique:[ etape('Mesures de Tension (V)','25 min',['Mesurer la tension batterie au repos, moteur tournant, et avec consommateurs actifs.','Mesurer les chutes de tension aux bornes des connexions positives et négatives.']), etape('Mesures de Résistance (Ω) et Continuité','30 min',['Tester la continuité d\'un fusible avec la fonction buzzer.','Mesurer la résistance d\'une sonde CTN/CTP à différentes températures.','Contrôler la continuité et l\'isolement d\'un faisceau électrique.']), etape('Validation et Interprétation','20 min',['Remplir un tableau de relevés de mesures.','Analyser les erreurs fréquentes (inversion des pointes, mauvais calibre) et comment les éviter.']) ], securiteRangement:['Couper le contact avant toute mesure de résistance','Ne jamais percer les isolants des fils','Ranger les cordons du multimètre après usage'], pointsCles:['Bon calibre','Polarité correcte','Sécurité électrique'] },
  3:{ id: 3, duree:'1h45', titre:'UE 202 • Contrôle circuit de démarrage', situation:'Un client se plaint que son véhicule refuse de démarrer. Le démarreur ne tourne pas. Vous devez diagnostiquer le circuit de démarrage pour identifier la cause de la panne.', objectif:'Identifier la cause d’un non-démarrage et valider le diagnostic. (Compétence C2.4)', materiel:['Multimètre','Schéma électrique','Pince ampèremétrique','Chargeur de batterie'], 
    etudePrelim:[
        {type: 'qcm', q:"Le démarreur ne tourne pas. Quelle est la première chose à contrôler ?", options: ["Le démarreur lui-même", "L'alternateur", "La tension et l'état des cosses de la batterie"], r:"La tension et l'état des cosses de la batterie"},
        {type: 'text', q:"Interprétation de mesure : Vous mesurez 12,5V à la batterie, mais seulement 9V sur la borne de commande (solénoïde) lorsque vous tournez la clé. Que suspectez-vous ?",r:'Une chute de tension importante sur le circuit de commande, probablement due à un mauvais contact sur le Neiman, un relais défectueux ou un faisceau endommagé.'},
        {type: 'text', q:"Analyse de schéma : Sur le schéma électrique du circuit de démarrage, identifiez le chemin exact du courant de commande (du Neiman au solénoïde) et celui du courant de puissance.",r:'Le courant de commande va de la batterie au Neiman, puis au relais de démarreur et enfin à la borne 50 du solénoïde. Le courant de puissance va directement de la borne + de la batterie à la borne 30 du démarreur.'}
    ], 
    activitePratique:[ etape('Contrôles Préliminaires','25 min',['Vérifier la tension de la batterie (>12,4 V).','Inspecter le serrage et l\'oxydation des cosses.','Contrôler la continuité des masses moteur et châssis.']), etape('Mesures Électriques','45 min',['Mesurer la tension en sortie du contacteur à clé (position Démarrage).','Vérifier la présence de 12V sur la borne 50 du démarreur.','Mesurer les chutes de tension sur le câble positif et la masse.','Mesurer l\'intensité au démarrage (doit être entre 150A et 300A).']), etape('Conclusion et Diagnostic','25 min',['Déterminer si la panne vient de la batterie, du câblage, du relais ou du démarreur.','Préconiser les actions correctives à mener.']) ], securiteRangement:['Prudence lors de la manipulation de la batterie','Ranger la pince ampèremétrique','Tracer toutes les mesures effectuées'], pointsCles:['Batterie OK en premier','Chutes de tension révélatrices','Intensité de démarrage élevée'] },
  4:{ id: 4, duree:'2h00', titre:'UE 207 • Contrôle du démarreur', situation:'Le diagnostic précédent a mis en cause le démarreur. Vous devez le déposer, le contrôler sur banc et le remplacer pour confirmer la panne et réparer le véhicule.', objectif:'Valider l’état du démarreur, le remplacer et effectuer un contrôle qualité. (Compétence C2.2)', materiel:['Banc de test démarreur','Multimètre','Jeu de clés','Pièces de rechange (solénoïde, balais)'], 
    etudePrelim:[
        {type: 'qcm', q:"Vous entendez un 'clac' mais le démarreur ne tourne pas. Quel composant est probablement fonctionnel et lequel est défaillant ?", options: ["Le solénoïde est HS, le moteur électrique est OK.", "Le solénoïde fonctionne, le moteur électrique est HS.", "Les deux sont HS."], r:"Le solénoïde fonctionne, le moteur électrique est HS."},
        {type: 'text', q:"Analyse de risque : Vous testez un démarreur sur un banc. Quelle est la mesure de sécurité la plus importante à prendre concernant la fixation du démarreur ?",r:'Le fixer très solidement dans un étau ou sur le banc. Le couple de démarrage est très violent et peut projeter le démarreur s\'il est mal fixé.'},
        {type: 'text', q:"Réflexion critique : Pourquoi un démarreur peut-il fonctionner parfaitement à vide sur le banc, mais ne pas entraîner le moteur une fois monté sur le véhicule ?",r:'Parce qu\'à vide, il n\'a aucune charge. Une fois monté, il doit vaincre la compression du moteur. S\'il est faible (usure des charbons, court-circuit partiel), il n\'aura pas assez de force pour le faire.'}
    ], 
    activitePratique:[ etape('Dépose du Démarreur','30 min',['Débrancher la batterie.','Déposer les câbles d\'alimentation et les fixations du démarreur.','Extraire le démarreur du véhicule.']), etape('Contrôles des Composants','40 min',['Mesurer les résistances de l\'inducteur et de l\'induit.','Vérifier l\'isolement à la masse.','Contrôler l\'état du solénoïde et des balais.']), etape('Test sur Banc','35 min',['Mesurer l\'intensité à vide (doit être < 80A).','Écouter les bruits anormaux et vérifier la rotation.','Effectuer un test en charge si le banc le permet.']), etape('Repose et Validation','15 min',['Respecter les couples de serrage.','Effectuer un test de démarrage sur le véhicule.']) ], securiteRangement:['Batterie débranchée avant toute intervention','Ranger et nettoyer le banc après usage','Nettoyer les pièces et le poste de travail'], pointsCles:['Contrôles d\'isolement','Usure des balais','Validation sur banc'] },
  5:{ id: 5, duree:'1h45', titre:'UE 201 • Contrôle circuit de charge', situation:'Le témoin de batterie s\'allume par intermittence. Le client craint une panne imminente. Vous devez contrôler le circuit de charge pour diagnostiquer le problème.', objectif:'Mesurer la tension de charge et les chutes de tension pour diagnostiquer. (Compétence C2.1)', materiel:['Multimètre','Pince ampèremétrique','Schéma électrique'], 
    etudePrelim:[
        {type: 'text', q:"Scénario : Moteur tournant, vous mesurez 13.9V aux bornes de la batterie, mais le témoin reste allumé. Quelle pourrait être la cause, autre que l'alternateur lui-même ?",r:'Le fil d\'excitation (borne L/D+) de l\'alternateur est peut-être coupé ou le voyant lui-même est en défaut, car la tension de charge est correcte.'},
        {type: 'qcm', q:"Analyse Cause à Effet : Une courroie d'accessoires détendue patine. Quel sera l'impact sur la tension de charge mesurée aux bornes de la batterie ?", options: ["Aucun, l'alternateur compensera", "La tension sera instable et souvent trop basse", "La tension sera trop élevée"], r:"La tension sera instable et souvent trop basse"},
        {type: 'text', q:"Formulation d'hypothèses : La tension de charge mesurée est de 15.5V. Citez deux composants qui pourraient être la cause de cette surcharge et expliquez pourquoi.",r:'1. Le régulateur de tension de l\'alternateur est défectueux et ne limite plus la tension. 2. Une mauvaise masse sur l\'alternateur peut fausser la mesure du régulateur.'}
    ], 
    activitePratique:[ etape('Mesures de Tension','35 min',['Mesurer la tension batterie au repos, au ralenti, puis à 2000 tr/min.','Activer les consommateurs et vérifier la stabilité de la tension.','Mesurer les chutes de tension sur les câbles +B et la masse.']), etape('Inspection Visuelle','30 min',['Contrôler l\'état et la tension de la courroie d\'accessoires.','Vérifier l\'oxydation des bornes de la batterie et de l\'alternateur.','Écouter les bruits anormaux provenant de l\'alternateur.']), etape('Conclusion Diagnostique','20 min',['Déterminer si la panne vient des connexions, de la courroie ou de l\'alternateur.','Proposer les actions correctives.']) ], securiteRangement:['Attention aux pièces en rotation (courroie, ventilateur)','Débrancher la batterie avant toute dépose','Tracer les résultats de mesures'], pointsCles:['Tension de charge correcte','Connexions propres et serrées','Bonne tension de la courroie'] },
  6:{ id: 6, duree:'2h00', titre:'UE 206 • Contrôle de l\'alternateur', situation:'Suite au diagnostic précédent, l\'alternateur est suspecté. Vous devez le déposer pour un contrôle détaillé de ses composants internes (pont de diodes, régulateur).', objectif:'Tester et remplacer les composants défectueux de l’alternateur. (Compétence C2.2)', materiel:['Banc de test alternateur','Multimètre','Jeu de diodes','Régulateur neuf'], 
    etudePrelim:[
        {type: 'qcm', q:"Un alternateur ne charge pas. Avec un multimètre en mode 'test diode', vous trouvez une valeur dans les deux sens sur une des diodes du pont. Quelle est votre conclusion ?", options: ["La diode est bonne", "La diode est en court-circuit (passante dans les deux sens)", "La diode est coupée (ne conduit dans aucun sens)"], r:"La diode est en court-circuit (passante dans les deux sens)"},
        {type: 'text', q:"Analyse de risque : Vous remplacez uniquement le régulateur sur un alternateur dont les roulements sont bruyants. Quelle est la conséquence probable à court terme ?",r:'Les roulements risquent de gripper, de détruire la courroie et de provoquer une panne majeure, rendant la première réparation inutile.'},
        {type: 'text', q:"Réflexion : Pourquoi est-il souvent plus pertinent économiquement et techniquement de remplacer l'alternateur complet plutôt que de changer un seul de ses composants internes ?",r:'Le coût de la main-d\'œuvre pour le démontage/remontage et le test des composants internes dépasse souvent le prix d\'un alternateur en échange standard, qui est garanti.'}
    ], 
    activitePratique:[ etape('Dépose de l\'Alternateur','25 min',['Débrancher la batterie, détendre la courroie.','Déconnecter les câbles et retirer les vis de fixation.','Extraire l\'alternateur du compartiment moteur.']), etape('Contrôles des Composants','45 min',['Mesurer la résistance du rotor (environ 3–5 Ω).','Contrôler la continuité du stator (environ 0,1–0,3 Ω).','Tester le pont de diodes (sens unique de passage).','Inspecter le régulateur et les balais.']), etape('Test sur Banc','35 min',['Vérifier que la tension de régulation est d\'environ 14V.','Mesurer l\'intensité nominale en charge.','Contrôler la stabilité sans surtension.']), etape('Repose et Validation','15 min',['Respecter les couples de serrage et la tension de la courroie.','Effectuer un test de charge sur le véhicule.']) ], securiteRangement:['Batterie débranchée','Ranger et nettoyer le banc de test','Nettoyer le poste de travail'], pointsCles:['Pont de diodes fonctionnel','Régulation de tension < 14,8V','Validation sur banc'] },
  7:{ id: 7, duree:'2h00', titre:'CA 209 • Fermeture centralisée', situation:'La télécommande de la voiture d\'un client ne fonctionne plus, l\'obligeant à utiliser la clé. Vous devez diagnostiquer le système de fermeture centralisée.', objectif:'Tester moteurs/commande, appairer la télécommande et effectuer les réglages. (Compétence C2.3)', materiel:['Valise de diagnostic','Multimètre','Télécommande neuve','Pile CR2032'], 
    etudePrelim:[
        {type: 'qcm', q:"La centralisation fonctionne avec la clé dans la serrure, mais pas avec la télécommande (pile neuve). Où orientez-vous votre diagnostic en priorité ?", options: ["Les moteurs de portes", "Le récepteur haute fréquence (RF) du véhicule ou la synchronisation de la clé", "Le fusible de la centralisation"], r:"Le récepteur haute fréquence (RF) du véhicule ou la synchronisation de la clé"},
        {type: 'text', q:"Analyse de panne : Aucune porte ne se verrouille, mais vous entendez le 'clac' des relais dans l'habitacle. Quelle est l'hypothèse la plus probable (panne électrique, mécanique ou de commande) ?",r:'Panne électrique. La commande (relais) fonctionne, mais l\'alimentation n\'arrive pas aux moteurs ou la masse est mauvaise.'},
        {type: 'text', q:"Recherche d'information : Dans quelle section de la documentation technique trouveriez-vous la procédure exacte de resynchronisation (appairage) d'une nouvelle télécommande ?",r:'Dans la section \'Équipements de confort\', \'Carrosserie\' ou \'Système de verrouillage\'.'}
    ], 
    activitePratique:[ etape('Diagnostic Initial','25 min',['Tester le fonctionnement avec la clé et la télécommande.','Lire les codes défauts dans le calculateur confort.','Vérifier la tension de la pile de la télécommande (doit être > 3V).']), etape('Contrôle des Actionneurs','50 min',['Vérifier l\'alimentation des moteurs de serrure (inversion de polarité).','Tester les microrupteurs de position de porte.','Contrôler l\'état et la continuité des faisceaux de porte.']), etape('Synchronisation de la Télécommande','30 min',['Vérifier l\'émission du signal (infrarouge ou radio).','Suivre la procédure d\'appairage du constructeur.','Valider le fonctionnement de la nouvelle télécommande.']) ], securiteRangement:['Attention aux clips de garniture de porte','Protéger les vitres lors des manipulations','Tracer la procédure d\'appairage'], pointsCles:['Tester la pile en premier','Moteur ou mécanisme ?','Procédure d\'appairage'] },
  8:{ id: 8, duree:'2h00', titre:'UE 211 • Diagnostic d\'un circuit électrique (feux stop)', situation:'Un client a été averti que ses feux stop ne s\'allument plus. Vous devez appliquer une méthode rigoureuse pour localiser et réparer la panne.', objectif:'Isoler la panne, la corriger et réaliser un contrôle qualité. (Compétence C2.4)', materiel:['Schéma électrique','Multimètre','Jeu de fusibles','Jeu d\'ampoules'], 
    etudePrelim:[
        {type: 'text', q:"Méthodologie : Expliquez en quoi consiste la méthode de diagnostic 'du point-milieu' et comment vous l'appliqueriez pour diagnostiquer cette panne de feux stop.",r:'On commence par tester un point au milieu du circuit (ex: la sortie du contacteur de stop). Si le courant passe, le problème est en aval. Sinon, il est en amont. Cela permet de diviser par deux la zone de recherche à chaque mesure.'},
        {type: 'qcm', q:"Le 3ème feu stop fonctionne, mais les deux autres non. Quelle est votre première hypothèse logique ?", options: ["Le fusible est grillé", "Le contacteur de pédale est HS", "Les ampoules des deux feux sont grillées ou le faisceau est coupé après la dérivation vers le 3ème feu"], r:"Les ampoules des deux feux sont grillées ou le faisceau est coupé après la dérivation vers le 3ème feu"},
        {type: 'text', q:"Analyse de schéma : Sur le schéma, identifiez si le contacteur de pédale de frein coupe le +12V ou la masse. Quelle est l'incidence sur la méthode de test ?",r:'Si le contacteur coupe le +12V, on doit mesurer 12V en entrée et en sortie (pédale appuyée). S\'il coupe la masse, on mesure la continuité vers la masse.'}
    ], 
    activitePratique:[ etape('Contrôles Simples','25 min',['Vérifier les ampoules et le fusible correspondant.','Inspecter les connecteurs et les points de masse.','Tester le fonctionnement du contacteur de pédale.']), etape('Mesures Ciblées','45 min',['Mesurer la tension en entrée et en sortie du contacteur.','Vérifier la continuité du faisceau jusqu\'aux feux arrière.','Mesurer la chute de tension au niveau de la masse.']), etape('Validation de la Réparation','20 min',['Effectuer la réparation nécessaire.','Recontrôler le fonctionnement complet des feux stop.']) ], securiteRangement:['Couper le contact avant de manipuler le circuit','Respecter les calibres des fusibles et sections de fils','Fixer correctement les faisceaux réparés'], pointsCles:['Utiliser le schéma électrique','Méthode du point-milieu','Mesures de tension et continuité'] },
  9:{ id: 9, duree:'1h45', titre:'UE 210 • Câblage des clignotants', situation:'Sur une maquette pédagogique, vous devez réaliser de A à Z le câblage fonctionnel du circuit de clignotants et de feux de détresse.', objectif:'Câbler un circuit conforme et effectuer le réglage de la fréquence. (Compétence C2.3)', materiel:['Centrale clignotante','Commodo','Ampoules 21W','Câbles et cosses diverses'], 
    etudePrelim:[
        {type: 'qcm', q:"Après câblage, vos clignotants flashent beaucoup trop vite. Quelle est la cause la plus probable ?", options: ["La batterie est trop chargée", "Une des ampoules est grillée ou a une mauvaise puissance", "La centrale clignotante est trop puissante"], r:"Une des ampoules est grillée ou a une mauvaise puissance"},
        {type: 'text', q:"Analyse de fonctionnement : Pourquoi les feux de détresse (warning) doivent-ils pouvoir fonctionner même si le contact du véhicule est coupé ?",r:'Pour des raisons de sécurité évidentes. Si le véhicule est en panne sur le bord de la route, il doit pouvoir signaler sa présence même si le moteur est coupé.'},
        {type: 'text', q:"Réflexion : Sur un véhicule moderne, la 'centrale clignotante' est souvent intégrée dans un calculateur (ex: BSI). Quels avantages cette intégration apporte-t-elle (diagnostic, fonctionnalités) ?",r:'Cela permet un diagnostic via la valise, des fonctions confort (ex: clignotement 3 fois sur impulsion), et une meilleure fiabilité (pas de pièce mécanique).'}
    ], 
    activitePratique:[ etape('Câblage sur Maquette','40 min',['Alimenter la centrale clignotante.','Câbler le commodo pour les directions Gauche/Droite.','Relier les ampoules Avant/Arrière de chaque côté.']), etape('Tests et Validation','40 min',['Vérifier le fonctionnement des clignotants Gauche et Droit.','Câbler et tester la fonction feux de détresse (warning).','Mesurer la fréquence de clignotement et la valider.']), etape('Application sur Véhicule','25 min',['Identifier la centrale clignotante sur un véhicule réel.','Contrôler le relais et les ampoules correspondantes.','Tracer le schéma de câblage réalisé.']) ], securiteRangement:['Débrancher la maquette après usage','Ranger les câbles et cosses','Archiver le schéma de câblage'], pointsCles:['Rôle de la centrale','Warning = test global','Fréquence de clignotement'] },
  10:{ id: 10, duree:'2h00', titre:'UE 205 • Câblage d\'un circuit de moto-ventilateur', situation:'Sur maquette, vous devez câbler un circuit de refroidissement moteur complet, incluant Petite Vitesse (PV) et Grande Vitesse (GV) via des relais et une résistance.', objectif:'Réaliser un montage, valider les déclenchements et effectuer les réglages. (Compétence C2.3)', materiel:['Relais double','Résistance de puissance (PV)','Sonde de température','Fusibles 40A'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de conception : Quel est l'intérêt d'avoir deux vitesses de ventilation plutôt qu'une seule ? Pensez en termes de consommation d'énergie et de bruit.",r:'La petite vitesse est plus silencieuse et consomme moins d\'énergie, elle est suffisante pour la régulation dans la plupart des cas (embouteillages). La grande vitesse est une sécurité pour les situations extrêmes (fortes chaleurs, charge importante).'},
        {type: 'qcm', q:"La grande vitesse (GV) fonctionne, mais la petite vitesse (PV) ne se déclenche jamais. Quel composant spécifique est très probablement en cause ?", options: ["Le fusible principal du motoventilateur", "La résistance de puissance pour la petite vitesse", "Le relais de grande vitesse"], r:"La résistance de puissance pour la petite vitesse"},
        {type: 'text', q:"Analyse de schéma : Sur le schéma du circuit, où placeriez-vous votre pince ampèremétrique pour mesurer uniquement l'intensité consommée par le motoventilateur, sans inclure celle des bobines de relais ?",r:'Directement sur le câble d\'alimentation principal du moteur du ventilateur, après les relais.'}
    ], 
    activitePratique:[ etape('Câblage du Circuit','50 min',['Câbler l\'alimentation + batterie via le fusible de puissance.','Brancher les relais Petite Vitesse et Grande Vitesse.','Intégrer la résistance pour la commande PV du motoventilateur.']), etape('Tests et Mesures','45 min',['Mesurer l\'intensité en PV (environ 10A).','Mesurer l\'intensité en GV (environ 25A).','Valider le déclenchement via le thermocontact ou la commande de diagnostic.']), etape('Application sur Véhicule','25 min',['Identifier les relais et la résistance sur un véhicule réel.','Vérifier les déclenchements PV/GV.']) ], securiteRangement:['Débrancher la maquette après usage','Fixer solidement les câbles de puissance','Tracer le schéma réalisé'], pointsCles:['Résistance = PV','Intensités distinctes','Rôle des relais'] },
  11:{ id: 11, duree:'1h45', titre:'ME 205 • Contrôle circuit moto-ventilation refroidissement', situation:'Un véhicule a tendance à chauffer dans les embouteillages. Vous devez contrôler le circuit de moto-ventilation pour diagnostiquer le problème.', objectif:'Valider PV/GV, les températures de déclenchement et effectuer un contrôle qualité. (Compétence C2.4)', materiel:['Valise de diagnostic','Multimètre','Thermomètre infrarouge','Schéma électrique'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de données : La valise diag indique une température d'eau de 98°C, le motoventilateur est arrêté. Est-ce normal ? Quelles informations vous manquent pour conclure ?",r:'Ce n\'est probablement pas normal. Il manque la température de déclenchement de la petite vitesse préconisée par le constructeur (souvent autour de 92-96°C).'},
        {type: 'qcm', q:"Le motoventilateur tourne en permanence, même moteur froid. Quelle est l'hypothèse la plus probable ?", options: ["La batterie est faible", "Le thermocontact est bloqué en position fermée ou un relais est collé", "Le moteur du ventilateur est usé"], r:"Le thermocontact est bloqué en position fermée ou un relais est collé"},
        {type: 'text', q:"Réflexion critique : Pourquoi est-il plus fiable de forcer l'activation du ventilateur via la valise de diagnostic que de simplement shunter le relais ?",r:'La valise de diag teste toute la chaîne de commande (calculateur, faisceau, relais, moteur), alors que shunter le relais ne teste que le circuit de puissance à partir du relais.'}
    ], 
    activitePratique:[ etape('Test Fonctionnel','35 min',['Laisser le moteur monter en température.','Observer le déclenchement de la PV, puis de la GV.','Mesurer le temps de refroidissement.']), etape('Contrôles Électriques','40 min',['Vérifier l\'alimentation 12V des relais.','Mesurer les intensités consommées en PV et GV.','Contrôler la chute de tension à la masse (< 0,3V).']), etape('Diagnostic via Outil','30 min',['Lire les codes défauts dans l\'ECU.','Forcer l\'activation de la PV et de la GV via la valise.','Établir des préconisations de réparation.']) ], securiteRangement:['Laisser refroidir le moteur avant intervention','Débrancher la valise de diagnostic proprement','Tracer les résultats'], pointsCles:['Séquence PV → GV','Intensités cohérentes','Températures de déclenchement'] },
  12:{ id: 12, duree:'2h00', titre:'CA 210 • Vitres électriques', situation:'La vitre électrique côté passager ne fonctionne plus, ni depuis la commande conducteur, ni depuis la commande passager. Vous devez en trouver la cause.', objectif:'Discriminer panne moteur/mécanique/commande et remplacer l’élément défectueux. (Compétence C2.2)', materiel:['Multimètre','Graisse silicone','Outils de dégarnissage','Schéma électrique'], 
    etudePrelim:[
        {type: 'qcm', q:"La vitre descend mais ne remonte pas. Le problème est-il probablement le moteur lui-même, ou plutôt sa commande (l'interrupteur) ?", options: ["Le moteur est HS", "C'est probablement la commande (interrupteur) qui est défectueuse sur la fonction 'montée'", "C'est un problème mécanique"], r:"C'est probablement la commande (interrupteur) qui est défectueuse sur la fonction 'montée'"},
        {type: 'text', q:"Scénario : Après avoir débranché la batterie, la vitre passager fonctionne par à-coups et l'anti-pincement ne marche plus. Quelle est l'action corrective immédiate à réaliser ?",r:'Il faut réinitialiser le système. La procédure consiste généralement à maintenir le bouton en position montée pendant quelques secondes une fois la vitre fermée.'},
        {type: 'text', q:"Réflexion : Pourquoi un moteur de lève-vitre possède-t-il une protection thermique interne ?",r:'Pour éviter la surchauffe et un risque d\'incendie si on maintient le bouton appuyé alors que la vitre est déjà en butée (haute ou basse).'}
    ], 
    activitePratique:[ etape('Diagnostic Initial','25 min',['Tester les commandes conducteur et passager.','Vérifier le fusible correspondant aux lève-vitres.','Contrôler que le verrouillage enfant n\'est pas activé.']), etape('Contrôles Électriques','45 min',['Mesurer l\'alimentation du moteur (inversion +/- 12V).','Mesurer la résistance du moteur (environ 5–15 Ω).','Tester la continuité de l\'interrupteur inverseur.']), etape('Contrôles Mécaniques','35 min',['Inspecter l\'état des rails et des câbles.','Graisser le mécanisme si nécessaire.','Vérifier l\'état des butées.']), etape('Initialisation','15 min',['Effectuer des cycles complets montée/descente pour réapprendre les butées.','Tester le bon fonctionnement de l\'anti-pincement.']) ], securiteRangement:['Protéger les garnitures de porte','Protéger les vitres lors des manipulations','Tracer l\'intervention'], pointsCles:['Panne moteur vs mécanique','Nécessité d\'initialisation','Graissage du mécanisme'] },
  13:{ id: 13, duree:'1h45', titre:'CA 208 • Diagnostic essuie-vitre', situation:'Les essuie-glaces d\'un véhicule fonctionnent de manière erratique : la vitesse intermittente ne marche plus et ils ne reviennent pas à leur position de repos ("parking").', objectif:'Identifier le défaut (moteur/relais/commodo/parking) et le réparer. (Compétence C2.2)', materiel:['Multimètre','Relais de test','Jeu de fusibles','Schéma électrique'], 
    etudePrelim:[
        {type: 'qcm', q:"Les essuie-glaces fonctionnent en vitesse rapide, mais pas en vitesse lente. Où se situe probablement le défaut : dans le commodo, le moteur, ou le relais ?", options: ["Dans le moteur", "Dans le commodo ou le relais de vitesse lente", "Le fusible est grillé"], r:"Dans le commodo ou le relais de vitesse lente"},
        {type: 'text', q:"Scénario : Les essuie-glaces s'arrêtent au milieu du pare-brise lorsque vous les coupez. Quel composant spécifique est très probablement en panne ?",r:'Le contacteur de \'position de repos\' (ou \'parking\') situé à l\'intérieur du moteur d\'essuie-glace.'},
        {type: 'text', q:"Réflexion : Pourquoi les moteurs d'essuie-glace modernes intègrent-ils souvent leur propre électronique plutôt que de dépendre de relais externes ?",r:'Pour gérer des fonctions plus complexes comme la cadence variable, la détection de pluie, et pour réduire le nombre de pièces et la complexité du faisceau.'}
    ], 
    activitePratique:[ etape('Diagnostic Fonctionnel','25 min',['Tester toutes les positions du commodo.','Vérifier le fusible correspondant.','Tester le fonctionnement du lave-glace.']), etape('Contrôles Électriques','50 min',['Vérifier l\'alimentation du moteur d\'essuie-glace.','Tester la continuité des différentes positions du commodo.','Contrôler le relais d\'intermittence.','Vérifier le signal du contacteur de "parking".']), etape('Contrôles Mécaniques','25 min',['Inspecter l\'état de la biellette et des axes.','Vérifier la tension du ressort des bras.','Contrôler le fonctionnement de la pompe de lave-glace.']) ], securiteRangement:['Couper le contact avant intervention','Ranger les caches et protections','Tracer le diagnostic'], pointsCles:['Test du commodo','Rôle du relais','Position "parking"'] },
  14:{ id: 14, duree:'3h00', titre:'MTE 203 • Remplacement distribution et pompe à eau', situation:'Un véhicule arrive à l\'échéance de remplacement de sa courroie de distribution. L\'intervention inclut préventivement le remplacement de la pompe à eau.', objectif:'Respecter la procédure constructeur, le calage et remplacer les pièces. (Compétence C2.2)', materiel:['Kit de distribution','Jeu de piges de calage','Clé dynamométrique','Liquide de refroidissement'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de risque : Quelle est la conséquence catastrophique d'un décalage, même d'une seule dent, sur un moteur dit à 'interférence' ?",r:'Les soupapes et les pistons entreraient en collision, ce qui causerait des dommages très importants et coûteux au moteur (soupapes tordues, pistons marqués).'},
        {type: 'text', q:"Réflexion critique : Pourquoi est-il impératif de remplacer la pompe à eau et les galets en même temps que la courroie, même s'ils ne semblent pas usés ?",r:'Car ils ont la même durée de vie que la courroie. Un galet ou une pompe qui lâche peut détruire la courroie neuve, entraînant les mêmes conséquences qu\'une courroie cassée.'},
        {type: 'qcm', q:"Après avoir monté la nouvelle courroie, vous devez effectuer deux tours complets du vilebrequin à la main. Quel est le double objectif de cette étape cruciale ?", options: ["Pour bien tendre la courroie", "Pour vérifier l'absence de point dur (collision) et s'assurer que les repères de calage reviennent en place", "Pour lubrifier la nouvelle courroie"], r:"Pour vérifier l'absence de point dur (collision) et s'assurer que les repères de calage reviennent en place"}
    ], 
    activitePratique:[ etape('Calage et Préparation','35 min',['Déposer les protections et carters.','Aligner les repères et insérer les piges de calage (vilo/AAC).','Marquer le sens de rotation de l\'ancienne courroie.']), etape('Remplacement des Composants','90 min',['Remplacer la pompe à eau, les galets tendeurs et enrouleurs.','Poser la nouvelle courroie en respectant le sens.','Appliquer la tension préconisée à l\'aide de l\'outil spécifique.','Effectuer deux tours moteur manuels et recontrôler le calage.']), etape('Finition et Validation','35 min',['Remplir et purger le circuit de refroidissement.','Contrôler l\'absence de fuites et de bruits anormaux.','Documenter l\'intervention avec traçabilité des pièces.']) ], securiteRangement:['Batterie débranchée','Respect strict des couples de serrage','Propreté des plans de joint'], pointsCles:['Calage moteur exact','Tension correcte de la courroie','Purge du circuit de refroidissement'] },
  15:{ id: 15, duree:'2h00', titre:'MTE 208 • Relevé compression / fuite', situation:'Un moteur essence manque de puissance et présente un ralenti instable. Un relevé des compressions est nécessaire pour évaluer l\'état de santé du moteur.', objectif:'Identifier un cylindre faible, localiser la fuite et réaliser un contrôle qualité. (Compétence C2.4)', materiel:['Compressiomètre','Testeur de fuite cylindre (air 6–8 bar)','Jeu de clés à bougie','Burette d\'huile'], 
    etudePrelim:[
        {type: 'text', q:"Interprétation de données : Compression Cyl.1=12b, Cyl.2=11.5b, Cyl.3=7b, Cyl.4=12b. Quelle est votre première conclusion ? Quelle est la prochaine étape de votre diagnostic ?",r:'Le cylindre 3 a un problème d\'étanchéité. L\'étape suivante est de refaire le test après avoir mis une cuillère d\'huile dans ce cylindre.'},
        {type: 'qcm', q:"Lors du test de fuite sur le Cyl.3, vous entendez un sifflement d'air dans le pot d'échappement. Quelle soupape est probablement en cause ?", options: ["La soupape d'admission", "La soupape d'échappement", "Aucune, c'est normal"], r:"La soupape d'échappement"},
        {type: 'text', q:"Scénario : Après avoir ajouté de l'huile dans le Cyl.3, la compression remonte à 10b. Vers quelle partie du moteur votre diagnostic s'oriente-t-il désormais ?",r:'Vers la segmentation (segments/pistons). L\'huile a temporairement amélioré l\'étanchéité, ce qui indique que le problème ne vient pas des soupapes.'}
    ], 
    activitePratique:[ etape('Préparation du Test','25 min',['Faire chauffer le moteur.','Déposer toutes les bougies d\'allumage ou injecteurs.','Couper l\'allumage et l\'injection pour le test.']), etape('Test de Compression','50 min',['Actionner le démarreur pendant 5 à 7 tours pour chaque cylindre.','Relever et noter la pression de chaque cylindre.','Si un cylindre est faible, refaire le test après avoir injecté une cuillère d\'huile.']), etape('Test de Fuite','40 min',['Positionner le cylindre faible au PMH compression.','Injecter de l\'air sous pression (6 bar) et mesurer le pourcentage de fuite.','Écouter où l\'air s\'échappe : admission, échappement, reniflard, radiateur.']) ], securiteRangement:['Débrancher la batterie avant dépose','Respecter le couple de serrage des bougies','Tracer tous les relevés de mesure'], pointsCles:['Écart < 10% entre cylindres','Segmentation / Soupapes / Joint de culasse','Position PMH exacte'] },
  16:{ id: 16, duree:'2h00', titre:'AS 209 • Pré-contrôle technique', situation:'Un client souhaite faire un bilan complet de son véhicule avant de le présenter au contrôle technique officiel afin d\'éviter une contre-visite.', objectif:'Préparer le véhicule à la visite et réaliser un contrôle qualité final. (Compétence C2.4)', materiel:['Check-list officielle du contrôle technique','Lecteur EOBD','Luxmètre','Manomètre de pression pneus'], 
    etudePrelim:[
        {type: 'text', q:"Jeu de rôle : Vous détectez une usure irrégulière des pneus. Comment l'expliquez-vous au client et quelle prestation complémentaire lui proposez-vous ?",r:'J\'explique que l\'usure anormale est souvent due à un défaut de géométrie des trains roulants, ce qui est un motif de contre-visite. Je lui propose un contrôle et un réglage de la géométrie.'},
        {type: 'qcm', q:"Un code défaut moteur est présent mais le témoin est éteint. Le véhicule passera-t-il le contrôle technique ?", options: ["Oui, si le témoin est éteint, tout va bien", "Non, la simple présence d'un code défaut dans le calculateur est un motif de contre-visite depuis 2019", "Peut-être, ça dépend du code"], r:"Non, la simple présence d'un code défaut dans le calculateur est un motif de contre-visite depuis 2019"},
        {type: 'text', q:"Prise de décision : Le client refuse la réparation d'une défaillance 'majeure'. Quelle mention devez-vous absolument faire figurer sur l'OR avant de lui restituer le véhicule ?",r:'Il faut écrire "Le client refuse la réparation de [défaut]. Le véhicule est susceptible d\'être refusé au contrôle technique et présente un risque pour la sécurité." et le faire signer.'}
    ], 
    activitePratique:[ etape('Contrôles Visuels Majeurs','35 min',['Vérifier l\'éclairage, le vitrage, la corrosion perforante.','Inspecter l\'usure et la pression des pneus, les fuites visibles, l\'état de l\'échappement.']), etape('Mesures et Diagnostics','35 min',['Contrôler le réglage des phares avec le luxmètre.','Ajuster la pression des pneus.','Effectuer une lecture des codes défauts via la prise OBD.']), etape('Restitution et Préconisations','20 min',['Lister les défaillances constatées et leur niveau de gravité (mineur, majeur, critique).','Fournir des préconisations chiffrées de remise en état.']) ], securiteRangement:['Respecter les consignes de sécurité de l\'atelier','Ranger tous les outils de mesure','Archiver la fiche de pré-contrôle'], pointsCles:['Respect du cadre réglementaire','Calculateur "propre" (sans DTC)','Traçabilité des défauts'] },
  17:{ id: 17, duree:'2h00', titre:'MTE 210 • Pression d\'huile (circuit de lubrification)', situation:'Le témoin de pression d\'huile s\'allume par intermittence au ralenti. Vous devez mesurer la pression d\'huile pour diagnostiquer une éventuelle défaillance du circuit.', objectif:'Mesurer la pression ralenti/3000 tr/min et préparer le diagnostic. (Compétence C2.1)', materiel:['Manomètre de pression d\'huile (0–10 bar)','Adaptateur pour capteur de pression','Multimètre','Documentation technique (RTA)'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de données : Pression à chaud : 0.5 bar au ralenti, 2.0 bar à 3000 tr/min. Le problème vient-il probablement de la pompe à huile elle-même ou de l'usure générale du moteur (coussinets) ? Justifiez.",r:'L\'usure générale du moteur. La pompe semble capable de fournir de la pression à haut régime, mais les jeux internes excessifs (coussinets) font chuter la pression au ralenti.'},
        {type: 'qcm', q:"Vous venez de faire la vidange avec une huile 0W20 au lieu de 5W40 préconisée. Quel impact cela aura-t-il sur la pression d'huile à chaud ?", options: ["Aucun, la viscosité ne change rien", "La pression sera plus élevée", "La pression sera plus faible car l'huile est plus fluide à chaud"], r:"La pression sera plus faible car l'huile est plus fluide à chaud"},
        {type: 'text', q:"Formulation d'hypothèses : Le témoin s'allume, mais la pression mesurée au manomètre est correcte. Citez deux causes possibles pour ce symptôme contradictoire.",r:'1. Le capteur de pression d\'huile (manocontact) est défectueux. 2. Il y a un problème électrique sur le faisceau entre le capteur et le tableau de bord.'}
    ], 
    activitePratique:[ etape('Installation du Manomètre','30 min',['Faire chauffer le moteur.','Déposer le capteur de pression d\'huile et installer le manomètre.','Vérifier le niveau et la viscosité de l\'huile.']), etape('Mesures de Pression','50 min',['Mesurer la pression au ralenti (doit être > 1–2 bar).','Mesurer la pression à 3000 tr/min (doit être de 3–6 bar).','Observer la stabilité de la pression.']), etape('Pré-Diagnostic','30 min',['Orienter le diagnostic : filtre colmaté, huile inadaptée, pompe, clapet, coussinets.','Corréler avec d\'éventuels codes défauts du calculateur.']) ], securiteRangement:['Attention à l\'huile chaude','Nettoyer toute fuite après dépose du manomètre','Tracer les pressions relevées'], pointsCles:['Pression cible atteinte','Stabilité de la pression','Identification des causes possibles'] },
  18:{ id: 18, duree:'2h00', titre:'MA 201 • Contrôle pression et débit essence', situation:'Un véhicule essence présente des pertes de puissance. Vous devez contrôler le circuit d\'alimentation basse pression pour vérifier la pompe à essence.', objectif:'Vérifier la régulation et le débit de la pompe avant une intervention. (Compétence C2.1)', materiel:['Manomètre de pression essence (0–6 bar)','Éprouvette graduée','Documentation technique (RTA)'], 
    etudePrelim:[
        {type: 'qcm', q:"La pression est correcte au ralenti, mais elle chute fortement lors d'une accélération franche. Le problème est-il plutôt la pompe, le régulateur ou le filtre à essence ?", options: ["Le régulateur", "La pompe est faible ou le filtre est colmaté, empêchant un débit suffisant", "Le réservoir est vide"], r:"La pompe est faible ou le filtre est colmaté, empêchant un débit suffisant"},
        {type: 'text', q:"Analyse de panne : Vous coupez le contact, la pression chute immédiatement à zéro. Quel composant du circuit est certainement défectueux ?",r:'Le clapet anti-retour de la pompe à essence.'},
        {type: 'text', q:"Analyse de risque : Pourquoi est-il particulièrement dangereux d'intervenir sur le circuit d'alimentation en essence d'un moteur à injection directe (GDI) ?",r:'Parce que la pression dans la rampe haute pression peut atteindre plus de 200 bars, même moteur coupé. Une déconnexion peut provoquer un jet de carburant extrêmement fin, inflammable et dangereux.'}
    ], 
    activitePratique:[ etape('Mesure de Pression','40 min',['Brancher le manomètre, mettre le contact : observer la montée en pression.','Mesurer au ralenti et en phase d\'accélération.','Couper le moteur et vérifier le maintien de la pression.']), etape('Mesure de Débit','40 min',['Dériver le circuit et mesurer le volume de carburant sur 30 secondes.','Extrapoler le débit en litres par minute.','Comparer la valeur à la préconisation constructeur.']) ], securiteRangement:['Assurer une bonne ventilation (vapeurs d\'essence)','Avoir un extincteur à proximité','Éliminer l\'essence récupérée dans les contenants adaptés'], pointsCles:['Pression correcte','Débit suffisant','Maintien de la pression'] },
  19:{ id: 19, duree:'2h00', titre:'MA 208 • Contrôle des injecteurs moteur diesel classique', situation:'Sur un moteur diesel ancienne génération, vous devez tester les injecteurs mécaniques sur un banc pour vérifier leur tarage et leur pulvérisation.', objectif:'Tester au banc, remplacer et conclure. (Compétence C2.2)', materiel:['Banc de test d\'injecteurs','Gasoil propre','Éprouvettes graduées'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de défaut : Un injecteur 'pisse' (laisse couler du gasoil) au lieu de pulvériser. Quelle sera la conséquence sur la combustion dans le cylindre concerné ?",r:'Une mauvaise combustion, provoquant de la fumée noire, des imbrûlés, un manque de puissance et potentiellement la fonte du piston à long terme.'},
        {type: 'qcm', q:"La pression d'ouverture d'un injecteur est trop basse. Comment cela va-t-il affecter le moment de l'injection et le bruit du moteur (claquements) ?", options: ["L'injection sera retardée et le moteur plus silencieux", "L'injection sera avancée et le moteur claquera davantage", "Ça n'a aucun effet"], r:"L'injection sera avancée et le moteur claquera davantage"},
        {type: 'text', q:"Réflexion : Pourquoi un joint d'injecteur non remplacé ou mal monté peut-il causer des dommages importants au moteur ?",r:'Une fuite sur le joint peut provoquer une perte de compression et permettre aux gaz de combustion de remonter et de \'coker\' l\'injecteur, le rendant inutilisable et difficile à démonter.'}
    ], 
    activitePratique:[ etape('Dépose des Injecteurs','30 min',['Nettoyer la zone de travail.','Déposer les lignes haute pression et les retours.','Extraire les injecteurs et leurs joints en cuivre.']), etape('Test sur Banc','60 min',['Mesurer la pression d\'ouverture (tarage).','Observer la forme du cône de pulvérisation.','Vérifier l\'étanchéité du nez de l\'injecteur.']), etape('Repose et Validation','30 min',['Utiliser des joints en cuivre neufs.','Serrer les injecteurs au couple préconisé.','Purger le circuit haute pression et démarrer.']) ], securiteRangement:['Protection des yeux obligatoire','Gérer les déchets de gasoil','Tracer les pressions relevées'], pointsCles:['Pression de tarage','Qualité de pulvérisation','Étanchéité parfaite'] },
  20:{ id: 20, duree:'2h30', titre:'F 204 • Remplacement maître-cylindre', situation:'La pédale de frein est spongieuse et s\'enfonce lentement. Le diagnostic indique une fuite interne du maître-cylindre. Vous devez le remplacer.', objectif:'Reposer et purger correctement pour réparer le circuit. (Compétence C2.2)', materiel:['Maître-cylindre neuf','Liquide de frein DOT 4','Appareil de purge sous pression','Clés à tuyauter'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de symptôme : Pédale spongieuse = Air dans le circuit. Pédale qui s'enfonce lentement au plancher = Fuite interne. Expliquez la différence physique entre ces deux défauts.",r:'Spongieuse : l\'air se comprime. Enfoncement lent : le liquide passe à travers les coupelles usées à l\'intérieur du maître-cylindre, il n\'y a pas de perte de liquide mais pas de maintien en pression.'},
        {type: 'qcm', q:"Pourquoi est-il conseillé de pré-remplir le maître-cylindre sur l'établi avant de le monter sur le véhicule ?", options: ["Pour le nettoyer", "Pour rendre la purge ultérieure beaucoup plus facile et rapide", "Ce n'est pas nécessaire"], r:"Pour rendre la purge ultérieure beaucoup plus facile et rapide"},
        {type: 'text', q:"Méthodologie : Quel est l'ordre de purge standard des roues et pourquoi cet ordre est-il si important ?",r:'Du plus loin au plus près du maître-cylindre (généralement ARD, ARG, AVD, AVG). Pour chasser l\'air progressivement dans tout le circuit sans en réintroduire.'}
    ], 
    activitePratique:[ etape('Dépose du Maître-cylindre','40 min',['Aspirer le liquide de frein du réservoir.','Débrancher les canalisations et les fixations.','Extraire le maître-cylindre.']), etape('Repose et Purge','60 min',['Pré-remplir le maître-cylindre neuf sur l\'établi.','Raccorder les canalisations.','Purger le circuit complet en respectant l\'ordre : ARD→ARG→AVD→AVG.']), etape('Validation','10 min',['Vérifier que la pédale est ferme.','Contrôler l\'absence totale de fuites.']) ], securiteRangement:['Liquide de frein corrosif (protéger la peinture)','Nettoyer immédiatement toute projection','Éliminer le liquide usagé via la filière agréée'], pointsCles:['Purge complète du circuit','Niveau du réservoir correct','Pédale dure et stable'] },
  21:{ id: 21, duree:'1h45', titre:'F 206 • Relevé de pressions de freinage', situation:'Pour diagnostiquer un déséquilibre de freinage, vous devez mesurer les pressions hydrauliques aux 4 roues à l\'aide de manomètres.', objectif:'Détecter les déséquilibres, localiser la cause et effectuer le réglage. (Compétence C2.1)', materiel:['Jeu de 4 manomètres haute pression','Adaptateurs de purge','Assistant pour actionner la pédale'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de données : Pression AVD=100b, AVG=60b, ARD=40b, ARG=40b. Quelle est l'anomalie principale et quel composant est probablement en cause ?",r:'Un déséquilibre avant important. La cause est probablement un étrier AVG grippé ou une canalisation bouchée.'},
        {type: 'qcm', q:"Les pressions avant sont bonnes mais vous n'avez quasiment aucune pression à l'arrière. Quelle est la cause la plus probable ?", options: ["Les plaquettes arrière sont neuves", "Le répartiteur de freinage est défectueux ou bloqué", "Le liquide de frein est trop vieux"], r:"Le répartiteur de freinage est défectueux ou bloqué"},
        {type: 'text', q:"Réflexion : Sur un véhicule sans ABS, le répartiteur de freinage est souvent asservi à la charge. Comment fonctionne-t-il et pourquoi ?",r:'Il est connecté au train arrière par un levier. Plus le véhicule est chargé, plus le levier ouvre le répartiteur pour donner plus de pression à l\'arrière, évitant ainsi un blocage des roues arrière à vide.'}
    ], 
    activitePratique:[ etape('Installation des Manomètres','30 min',['Brancher les manomètres sur les vis de purge de chaque roue.','Repérer clairement chaque manomètre (AVD, AVG, ARD, ARG).']), etape('Mesures de Pression','45 min',['Relever les pressions à mi-course et en pression maximale.','Comparer les pressions Avant/Arrière et Gauche/Droite.','Identifier et interpréter les déséquilibres.']) ], securiteRangement:['Déposer les manomètres proprement','Effectuer une purge si de l\'air a été introduit','Tracer tous les relevés'], pointsCles:['Symétrie des pressions','Pression AR < Pression AV','Rôle du répartiteur'] },
  22:{ id: 22, duree:'2h00', titre:'F 208 • Diagnostic du circuit de freinage avec passage au banc', situation:'Un véhicule doit passer au banc de freinage pour évaluer objectivement son efficacité et son équilibre avant le contrôle technique.', objectif:'Mesurer efficacité/équilibre/frein à main et effectuer un contrôle qualité. (Compétence C2.4)', materiel:['Banc de freinage à rouleaux','Fiche de résultats imprimée'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de résultats : Efficacité globale = 55% (OK). Déséquilibre AV = 15% (OK). Déséquilibre AR = 45% (KO). Quelle est votre conclusion sur l'état du véhicule ?",r:'Le véhicule sera refusé au contrôle technique à cause du déséquilibre arrière supérieur à 30%. Il y a un problème sur un des freins arrière (étrier grippé, cylindre de roue HS...).'},
        {type: 'qcm', q:"Le véhicule tire à droite lors du test sur le banc. Quelle est la cause la plus probable en dehors du système de freinage lui-même ?", options: ["Le volant n'est pas droit", "Un pneu avant est sous-gonflé", "Le moteur est trop puissant"], r:"Un pneu avant est sous-gonflé"},
        {type: 'text', q:"Réflexion critique : Pourquoi le test du frein de stationnement est-il aussi important pour la sécurité, même si on l'utilise peu en conduite ?",r:'Car il constitue un système de freinage de secours en cas de défaillance totale du circuit hydraulique principal.'}
    ], 
    activitePratique:[ etape('Préparation du Test','20 min',['Vérifier les pressions des pneus.','Effectuer une inspection visuelle rapide des freins.','Suivre les consignes de sécurité du banc.']), etape('Test Essieu Avant','30 min',['Mesurer les forces de freinage AVD et AVG.','Calculer le déséquilibre avant.']), etape('Test Essieu Arrière','30 min',['Mesurer les forces ARD et ARG.','Tester l\'efficacité du frein de stationnement.']), etape('Interprétation des Résultats','20 min',['Vérifier la conformité : efficacité totale > 50%, déséquilibre < 30%, frein à main > 16%.']) ], securiteRangement:['Sortir prudemment du banc de freinage','Ranger les équipements','Archiver la fiche de résultats'], pointsCles:['Efficacité de freinage','Équilibre G/D','Efficacité du frein à main'] },
  23:{ id: 23, duree:'2h00', titre:'F 209 • Diagnostic assistance au freinage', situation:'La pédale de frein d\'un véhicule est anormalement dure. Vous devez diagnostiquer le système d\'assistance au freinage (servofrein).', objectif:'Tester l’assistance, vérifier dépression/pression et remplacer les composants. (Compétence C2.1)', materiel:['Vacuomètre', 'Manomètre de pression', 'Valise de diagnostic', 'Schéma du système'], 
    etudePrelim:[
        { type: 'text', q: "Analyse de symptôme : Une pédale dure signifie un manque d'assistance. Comment différencier une panne du servofrein lui-même d'une panne de la source de dépression (pompe à vide ou collecteur d'admission) ?", r: 'On mesure la dépression à l\'entrée du servofrein. Si la dépression est bonne, le problème vient du servofrein. Si elle est mauvaise ou nulle, le problème vient de la source de dépression.' },
        { type: 'qcm', q: "Moteur tournant, vous débranchez la durite du servofrein et vous n'entendez aucune aspiration. Quelle est votre conclusion immédiate ?", options: ["Le servofrein est percé", "Il n'y a pas de dépression qui arrive au servofrein", "C'est normal"], r: "Il n'y a pas de dépression qui arrive au servofrein" },
        { type: 'text', q: "Réflexion : Sur un véhicule électrique, il n'y a pas de dépression moteur. Par quelle technologie l'assistance au freinage est-elle assurée ?", r: 'Par un système électro-hydraulique avec une pompe électrique qui génère de la pression, ou un système \'brake-by-wire\' entièrement électronique.' }
    ], 
    activitePratique:[ etape('Test Fonctionnel du Servofrein', '30 min', ['Moteur éteint, pomper plusieurs fois sur la pédale puis la maintenir enfoncée. Démarrer : la pédale doit s\'enfoncer légèrement.','Tester le maintien de la dépression après coupure du moteur.']),etape('Mesure de la Dépression', '40 min', ['Brancher le vacuomètre sur la durite entre la source (collecteur/pompe à vide) et le servofrein.','Mesurer la dépression au ralenti (environ -500 à -700 mbar).','Contrôler l\'étanchéité du clapet anti-retour et des durites.']),etape('Diagnostic Systèmes Hydrauliques (si équipé)', '35 min', ['Lire les codes défauts via la valise.','Mesurer la pression dans l\'accumulateur hydraulique.','Tester le capteur de pression et le contacteur de pédale.'])], securiteRangement:['Raccorder correctement les durites de dépression', 'Ranger les instruments de mesure', 'Tracer les mesures relevées'], pointsCles:['La pédale s\'enfonce au démarrage', 'Dépression suffisante et stable', 'Clapet anti-retour étanche'] },
  24:{ id: 24, duree:'4h00', titre:'T 201 • Dépose-pose embrayage', situation:'Un véhicule patine à l\'accélération. Le diagnostic confirme l\'usure de l\'embrayage. Vous êtes chargé du remplacement complet du kit (disque, mécanisme, butée).', objectif:'Remplacer le kit et valider un débrayage correct après réparation. (Compétence C2.2)', materiel:['Kit d\'embrayage neuf', 'Centreur d\'embrayage', 'Cric de fosse pour boîte de vitesses', 'Clé dynamométrique'], 
    etudePrelim:[
        { type: 'qcm', q: "Le moteur prend des tours mais la voiture n'accélère pas. C'est du patinage. Mais si les vitesses craquent au passage, quel autre symptôme cela indique-t-il ?", options: ["L'embrayage est neuf", "L'embrayage ne débraye plus correctement", "Le moteur est trop puissant"], r: "L'embrayage ne débraye plus correctement" },
        { type: 'text', q: "Réflexion critique : Pourquoi faut-il éviter de laisser la boîte de vitesses suspendue par l'arbre primaire lors de la dépose ?", r: 'Pour ne pas endommager l\'arbre primaire, le disque d\'embrayage ou le roulement pilote. Le poids de la boîte doit être supporté par un cric adapté.' },
        { type: 'text', q: "Méthodologie : Expliquez l'importance de serrer les vis du mécanisme d'embrayage progressivement et en étoile (ou en croix).", r: 'Pour appliquer une pression uniforme sur le diaphragme et le disque, éviter de voiler le mécanisme et assurer un contact parfait avec le volant moteur.' }
    ], 
    activitePratique:[ etape('Dépose de la Boîte de Vitesses', '80 min', ['Lever et sécuriser le véhicule sur pont.','Déposer les cardans, supports, tringlerie et connexions électriques.','Extraire la boîte de vitesses à l\'aide du cric de fosse.']),etape('Remplacement de l\'Embrayage', '50 min', ['Remplacer la butée et graisser son guide.','Centrer le disque neuf avec l\'outil spécifique.','Serrer le mécanisme en étoile et au couple préconisé.']),etape('Repose et Validation', '80 min', ['Accoupler et reposer la boîte de vitesses, les supports et cardans.','Rétablir la commande d\'embrayage (câble ou purge si hydraulique).','Effectuer un essai routier pour valider le point de touche et l\'absence de patinage.'])], securiteRangement:['Sécurité absolue lors du levage et de la dépose de la BV', 'Couples de serrage scrupuleusement respectés', 'Ranger et nettoyer l\'outillage'], pointsCles:['Centrage parfait du disque','Commande d\'embrayage correctement réglée','Essai routier validé'] },
  25:{ id: 25, duree:'2h30', titre:'T 208 • Remplacement commande d\'embrayage hydraulique', situation:'La pédale d\'embrayage est molle et reste parfois au plancher. Une fuite est détectée sur le circuit hydraulique (émetteur ou récepteur).', objectif:'Remplacer l’organe défectueux et purger correctement. (Compétence C2.2)', materiel:['Émetteur ou récepteur d\'embrayage', 'Liquide de frein DOT 4', 'Appareil de purge', 'Clés à tuyauter'], 
    etudePrelim:[
        { type: 'text', q: "Analyse de panne : La fuite est visible sur le récepteur, près de la boîte de vitesses. Quelle est la conséquence si le liquide de frein coule sur le disque d'embrayage ?", r: 'Le liquide contamine la garniture du disque, qui va patiner. L\'embrayage est alors à remplacer, même s\'il n\'est pas usé.' },
        { type: 'qcm', q: "Vous remplacez l'émetteur, mais la pédale reste molle après la purge. Quelle est la prochaine étape logique de votre diagnostic ?", options: ["Changer le liquide de frein", "Vérifier le récepteur et les canalisations, car il y a peut-être une autre fuite ou de l'air coincé", "Régler la garde de la pédale"], r: "Vérifier le récepteur et les canalisations, car il y a peut-être une autre fuite ou de l'air coincé" },
        { type: 'text', q: "Réflexion : Pourquoi utilise-t-on du liquide de frein pour une commande d'embrayage hydraulique et non de l'huile ?", r: 'Parce que le liquide de frein est incompressible, résiste à l\'ébullition et n\'endommage pas les joints en caoutchouc du circuit, contrairement à une huile minérale.' }
    ], 
    activitePratique:[ etape('Dépose de l\'Organe Défectueux', '40 min', ['Aspirer le liquide du bocal.','Débrancher les durites et les fixations.','Extraire l\'émetteur (côté pédalier) ou le récepteur (sur la boîte).']),etape('Repose et Purge du Circuit', '60 min', ['Monter l\'élément neuf.','Remplir avec du liquide de frein DOT 4 neuf.','Purger le circuit jusqu\'à disparition complète des bulles d\'air.']),etape('Validation de l\'Intervention', '10 min', ['Vérifier que la course de la pédale est normale.','Contrôler que les vitesses passent bien à l\'arrêt.','Documenter l\'intervention.'])], securiteRangement:['Liquide de frein corrosif (protéger la peinture)','Nettoyage immédiat de toute projection','Élimination des déchets selon les normes environnementales'], pointsCles:['Purge complète du circuit','Absence totale de fuites','Course de pédale validée'] },
  26:{ id: 26, duree:'3h00', titre:'T 206 • Découverte de la boîte de vitesses', situation:'Sur une boîte de vitesses déposée et destinée à la formation, vous devez effectuer un démontage partiel pour analyser son fonctionnement interne.', objectif:'Identifier pignons, synchros, arbres et fourchettes pour préparer une intervention. (Compétence C2.1)', materiel:['Boîte de vitesses didactique', 'Jeu d\'extracteurs', 'Bac de nettoyage', 'Schéma éclaté de la BV'], 
    etudePrelim:[
        { type: 'text', q: "Analyse fonctionnelle : Observez deux pignons de rapports différents. Pourquoi le pignon du 1er rapport est-il beaucoup plus grand que celui du 5ème rapport ?", r: 'Le 1er rapport a besoin de plus de couple (force) pour lancer le véhicule. Un grand pignon mené par un petit pignon moteur démultiplie la force (au détriment de la vitesse).' },
        { type: 'qcm', q: "Quel est le rôle des petites dents (crabots) sur le côté des pignons et des baladeurs de synchro ?", options: ["À lubrifier la boîte", "À freiner la rotation des pignons", "À verrouiller mécaniquement le pignon sur l'arbre une fois les vitesses synchronisées"], r: "À verrouiller mécaniquement le pignon sur l'arbre une fois les vitesses synchronisées" },
        { type: 'text', q: "Méthodologie : Pourquoi le repérage et le rangement méthodique des pièces (vis, rondelles, circlips) sont-ils absolument critiques lors du démontage d'une boîte de vitesses ?", r: 'Parce que chaque pièce a une place et une fonction précise. Une erreur de remontage peut bloquer la boîte ou entraîner sa destruction rapide.' }
    ], 
    activitePratique:[ etape('Ouverture de la Boîte', '50 min', ['Vidanger l\'huile de la boîte.','Ouvrir le carter de sélection et le carter principal.','Repérer les différents ensembles (arbres, différentiel).']), etape('Analyse des Composants', '80 min', ['Examiner l\'usure des bagues de synchro et des crabots.','Contrôler le jeu des roulements d\'arbres.','Observer le fonctionnement de la sélection et des fourchettes.']),etape('Remontage Partiel', '70 min', ['Remplacer les joints et les circlips si nécessaire.','Appliquer la graisse adaptée sur les points de friction.','Contrôler la libre rotation des arbres et le bon passage des rapports.'])], securiteRangement:['Recycler l\'huile de boîte usagée','Nettoyer les pièces avant analyse','Ranger l\'outillage spécifique (extracteurs)'], pointsCles:['Méthode et rigueur','Repérage des pièces','Analyse des jeux fonctionnels'] },
  27:{ id: 27, duree:'3h30', titre:'T 205 • Échange synchro 5e', situation:'Un véhicule présente un craquement systématique lors du passage de la 5ème vitesse. Le diagnostic pointe vers un synchroniseur usé. Vous devez le remplacer.', objectif:'Supprimer les craquements, remplacer le synchro et valider l’engagement. (Compétence C2.2)', materiel:['Kit synchroniseur 5ème vitesse', 'Jeu d\'extracteurs', 'Circlips neufs', 'Huile de boîte préconisée'], 
    etudePrelim:[
        { type: 'qcm', q: "Le passage 3ème -> 4ème craque, mais pas 4ème -> 3ème. La bague de synchro est-elle la seule cause possible ? Quelle autre pièce pourrait être en cause ?", options: ["Non, le crabot du pignon peut aussi être usé", "Oui, c'est forcément la bague", "C'est un problème d'huile"], r: "Non, le crabot du pignon peut aussi être usé" },
        { type: 'text', q: "Réflexion : Pourquoi la bague de synchroniseur est-elle souvent faite en laiton ou en bronze, un métal plus 'tendre' que les pignons en acier ?", r: 'C\'est une pièce d\'usure volontaire. Le métal tendre sert de cône de friction pour égaliser les vitesses de rotation. Il s\'use à la place des pignons qui sont plus chers et difficiles à remplacer.' },
        { type: 'text', q: "Méthodologie : Vous devez remonter un roulement sur un arbre. Préférez-vous utiliser une presse ou le chauffer légèrement ? Justifiez votre choix en termes de sécurité et de préservation des pièces.", r: 'Une presse est préférable. Elle applique une force contrôlée et droite. Chauffer un roulement peut altérer ses propriétés métallurgiques s\'il n\'est pas fait correctement dans un bain d\'huile à température contrôlée.' }
    ], 
    activitePratique:[ etape('Accès au Pignon de 5ème', '80 min', ['Déposer la boîte de vitesses du véhicule.','Ouvrir le carter de 5ème.','Bloquer l\'arbre pour desserrer l\'écrou de maintien.']), etape('Remplacement du Synchroniseur', '60 min', ['Extraire le pignon et le baladeur de 5ème.','Remplacer les bagues et les ressorts du synchroniseur.','Contrôler les jeux avec un comparateur.']),etape('Validation de la Réparation', '60 min', ['Remonter la boîte, faire le plein d\'huile.','Effectuer un essai routier en insistant sur le passage 4ème ↔ 5ème.','Documenter l\'intervention.'])], securiteRangement:['Recycler l\'huile usagée','Respecter les couples de serrage','Archiver les photos des étapes clés'], pointsCles:['Jeux fonctionnels corrects','Passage de vitesse doux','Absence de craquement validée'] },
  28:{ id: 28, duree:'1h30', titre:'L 204 • Effectuer un pré-contrôle géométrie', situation:'Avant de monter un véhicule sur le banc de géométrie 3D, un pré-contrôle rigoureux des trains roulants est indispensable pour garantir la fiabilité des mesures.', objectif:'Valider la préparation du véhicule avant de passer au banc 3D. (Compétence C2.1)', materiel:['Pont élévateur','Manomètre de pression pneus','Jauge de profondeur','Lampe d\'inspection'], 
    etudePrelim:[
        {type: 'text', q:"Analyse critique : Vous constatez une usure beaucoup plus prononcée sur le pneu avant droit que sur le gauche. Quelles sont les 3 hypothèses de défaut géométrique les plus probables ?",r:'1. Défaut de parallélisme (ouverture/pincement excessif). 2. Défaut de carrossage (angle de la roue). 3. Problème sur le train arrière qui fait \'marcher en crabe\' le véhicule.'},
        {type: 'qcm', q:"En secouant une roue, vous détectez un jeu important. Comment déterminez-vous si ce jeu provient de la rotule de direction ou du roulement de roue ?", options: ["C'est impossible à dire", "Le jeu de rotule est horizontal, celui du roulement est souvent vertical et diagonal", "Il faut tout démonter"], r:"Le jeu de rotule est horizontal, celui du roulement est souvent vertical et diagonal"},
        {type: 'text', q:"Réflexion : Pourquoi un simple réglage de géométrie est-il inutile et non professionnel si un silentbloc de bras de suspension est complètement déchiré ?",r:'Parce que le silentbloc déchiré introduit un jeu. Le réglage sera donc instable et faux. La position de la roue changera constamment en roulant, annulant le réglage.'}
    ], 
    activitePratique:[ etape('Contrôle des Pneumatiques', '20 min', ['Ajuster les pressions selon les préconisations.','Mesurer la profondeur des sculptures et vérifier l\'homogénéité.','Analyser les usures irrégulières (indices de défauts géométriques).']),etape('Contrôle du Train Avant', '35 min', ['Vérifier l\'absence de jeu dans les rotules de direction et de suspension.','Inspecter l\'état des silentblocs de bras de suspension.','Contrôler le jeu des roulements de roue et l\'état des amortisseurs.']),etape('Contrôle du Train Arrière', '25 min', ['Inspecter les bras de suspension et les biellettes.','Vérifier les fixations et l\'état des silentblocs.'])], securiteRangement:['Descendre le pont en sécurité','Ranger les outils de mesure','Remplir la fiche de pré-contrôle'], pointsCles:['Pressions conformes','Absence totale de jeu','Véhicule prêt pour le banc'] },
  29:{ id: 29, duree:'2h00', titre:'L 207 • Contrôler géométrie. Régler le parallélisme', situation:'Un véhicule tire à droite et présente une usure anormale des pneus avant. Un contrôle et un réglage de la géométrie sont nécessaires.', objectif:'Obtenir des valeurs dans tolérances et réaliser le réglage avec volant centré. (Compétence C2.3)', materiel:['Banc de géométrie 3D','Clés de réglage pour biellettes','Fiches de valeurs constructeur'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de données : Le rapport de géométrie indique : Para AV G = +0°10', Para AV D = -0°15'. Le véhicule va-t-il tirer ? Où l'usure des pneus sera-t-elle la plus forte ?",r:'Le véhicule va tirer à droite à cause du parallélisme total très ouvert. L\'usure sera forte sur le bord intérieur des deux pneus.'},
        {type: 'qcm', q:"Pourquoi doit-on commencer par régler le train arrière (si réglable) avant de toucher au train avant ?", options: ["C'est une habitude", "Parce que le train arrière est la base directionnelle du véhicule. Le train avant se règle par rapport à lui.", "C'est plus facile"], r:"Parce que le train arrière est la base directionnelle du véhicule. Le train avant se règle par rapport à lui."},
        {type: 'text', q:"Réflexion critique : Le client se plaint que son volant n'est plus droit après votre intervention, bien que le parallélisme soit parfait. Qu'avez-vous oublié de faire pendant le réglage ?",r:'J\'ai oublié de bloquer le volant parfaitement au centre avant de commencer le réglage et d\'ajuster les deux biellettes de manière symétrique.'}
    ], 
    activitePratique:[ etape('Mesure des Angles', '50 min', ['Effectuer la compensation du voile des jantes.','Lancer la lecture des angles des trains Avant et Arrière.','Identifier les valeurs hors tolérances par rapport aux données constructeur.']),etape('Réglage du Parallélisme', '40 min', ['Agir sur les biellettes de direction pour régler le parallélisme avant (et arrière si possible).','Effectuer des ajustements itératifs jusqu\'à obtenir des valeurs dans le vert.','Centrer parfaitement le volant pendant le réglage.']),etape('Validation Finale', '10 min', ['Imprimer les fiches de résultats Avant/Après.','Effectuer un court essai routier pour valider le comportement.']) ], securiteRangement:['Serrer fermement les contre-écrous des biellettes','Ranger et protéger les capteurs 3D','Archiver les fiches de mesure'], pointsCles:['Symétrie des réglages','Réglage itératif','Volant parfaitement centré'] },
  30:{ id: 30, duree:'2h30', titre:'L 213 • Découverte et entretien suspension hydraulique', situation:'Un véhicule équipé d\'une suspension hydropneumatique présente une assiette incorrecte. Vous devez diagnostiquer et entretenir le système.', objectif:'Contrôler assiette, pressions sphères, et réparer le circuit. (Compétence C2.1)', materiel:['Manomètre haute pression','Station de gonflage azote','Liquide hydraulique (LHM/LDS)','Valise de diagnostic'], 
    etudePrelim:[
        {type: 'qcm', q:"La suspension est extrêmement dure et 'tape' sur les bosses. Quel est le diagnostic le plus probable concernant les sphères ?", options: ["Les sphères sont trop gonflées", "Les sphères sont dégonflées ou leur membrane est percée, il n'y a plus d'amortissement par le gaz", "C'est normal pour ce type de suspension"], r:"Les sphères sont dégonflées ou leur membrane est percée, il n'y a plus d'amortissement par le gaz"},
        {type: 'text', q:"Analyse de risque : Pourquoi est-il vital de dépressuriser complètement le circuit hydraulique avant d'intervenir sur une sphère ou une canalisation ?",r:'Parce que le circuit est sous haute pression (jusqu\'à 170 bars). Une ouverture non contrôlée peut provoquer une projection violente de liquide, causant de graves blessures.'},
        {type: 'text', q:"Scénario : Vous remplacez le liquide LHM (vert) par du LDS (orange). Quelles seront les conséquences catastrophiques pour le système ?",r:'Le LDS (liquide de synthèse) va détruire tous les joints en caoutchouc conçus pour le LHM (liquide minéral), provoquant des fuites massives sur tout le système.'}
    ], 
    activitePratique:[ etape('Diagnostic de l\'Assiette', '40 min', ['Mesurer les hauteurs de caisse aux 4 coins.','Comparer les valeurs aux tolérances constructeur.','Lire les codes défauts du calculateur de suspension.']), etape('Contrôle des Sphères', '50 min', ['Dépressuriser le circuit.','Mesurer et regonfler la pression d\'azote de chaque sphère.','Remplacer une sphère si sa membrane est défectueuse.']),etape('Purge et Validation', '50 min', ['Compléter le niveau de liquide hydraulique.','Purger le circuit et actionner les différentes hauteurs.','Effectuer un essai pour valider le confort et la réactivité.']) ], securiteRangement:['Utiliser uniquement de l\'azote pour le gonflage','Protection des yeux obligatoire','Éliminer le liquide hydraulique usagé correctement'], pointsCles:['Pression des sphères = confort','Correction d\'assiette','Purge du circuit'] },
  31:{ id: 31, duree:'1h45', titre:'MTE 202 • Contrôle étanchéité circuit de refroidissement', situation:'Une odeur de liquide de refroidissement est perceptible et le niveau baisse légèrement. Vous devez mettre le circuit sous pression pour localiser la fuite.', objectif:'Pressuriser, traquer les fuites et effectuer un contrôle qualité final. (Compétence C2.4)', materiel:['Pompe de test d\'étanchéité avec manomètre','Adaptateur de bouchon de radiateur','Traceur UV et lampe UV'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de risque : Pourquoi est-il impératif d'effectuer ce test sur un moteur complètement FROID ?",r:'Un circuit chaud est sous pression. L\'ouvrir présente un risque de brûlure grave par projection de liquide chaud.'},
        {type: 'qcm', q:"Vous mettez le circuit sous pression et celle-ci chute lentement, mais aucune fuite n'est visible à l'extérieur. Quelles sont vos deux principales hypothèses ?", options: ["C'est normal, il y a une évaporation", "Le radiateur de chauffage fuit dans l'habitacle, ou le joint de culasse est défectueux", "Le manomètre est en panne"], r:"Le radiateur de chauffage fuit dans l'habitacle, ou le joint de culasse est défectueux"},
        {type: 'text', q:"Réflexion : La pression de test est généralement de 1,2 bar. Le bouchon du vase d'expansion est souvent taré à 1,4 bar. Pourquoi cette différence ?",r:'Pour éviter d\'endommager un élément du circuit (radiateur, durite) en appliquant une pression supérieure à celle pour laquelle il est conçu. On teste en dessous de la pression maximale de sécurité.'}
    ], 
    activitePratique:[ etape('Test de Pression à Froid', '50 min', ['Moteur froid, mettre le circuit sous pression (1,2 à 1,6 bar).','Observer si la pression chute sur le manomètre et localiser les points humides.','Utiliser le traceur UV si la fuite est difficile à localiser.']),etape('Contrôles Complémentaires', '30 min', ['Utiliser un kit de détection de CO2 pour rechercher des gaz d\'échappement dans le liquide.','Vérifier l\'absence d\'huile émulsionnée ("mayonnaise").']),etape('Conclusion et Réparation', '10 min', ['Localiser précisément la fuite.','Effectuer un re-test d\'étanchéité après la réparation.']) ], securiteRangement:['Intervenir exclusivement sur moteur froid','Relâcher la pression avant toute déconnexion','Tracer la localisation de la fuite'], pointsCles:['La pression doit tenir','Traceur UV pour fuites discrètes','Recherche de CO2 pour le joint de culasse'] },
  32:{ id: 32, duree:'2h00', titre:'MA 202 • Diagnostic (prise en main matériel). Lecture paramètres', situation:'Pour initier un diagnostic sur un véhicule moderne, le chef d\'atelier vous demande de vous connecter au calculateur moteur pour lire les codes défauts et analyser les paramètres clés.', objectif:'Lire/interpréter les données pour préparer une intervention. (Compétence C2.1)', materiel:['Valise de diagnostic multimarque','Chargeur de maintien de tension','Adaptateurs OBD'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de données : Les 'données figées' (freeze frame) d'un code défaut indiquent T° moteur = 25°C, Régime = 2800 tr/min, Charge = 80%. Que pouvez-vous déduire sur les conditions d'apparition de la panne ?",r:'La panne est survenue moteur froid, lors d\'une forte accélération, peu après le démarrage.'},
        {type: 'text', q:"Réflexion critique : Pourquoi est-il méthodologiquement incorrect d'effacer les codes défauts sans les avoir notés et analysés au préalable ?",r:'Parce qu\'on perd des informations cruciales sur l\'origine de la panne (codes, données figées). Certains défauts peuvent être intermittents et ne pas réapparaître tout de suite.'},
        {type: 'qcm', q:"Vous lisez une valeur de pression de suralimentation de 1.5 bar, moteur à l'arrêt. Quelle est votre première conclusion logique ?", options: ["Le turbo est très performant", "Le capteur de pression de suralimentation est défectueux ou son câblage est en court-circuit", "C'est normal"], r:"Le capteur de pression de suralimentation est défectueux ou son câblage est en court-circuit"}
    ], 
    activitePratique:[ etape('Connexion et Lecture Initiale', '25 min', ['Brancher l\'outil de diagnostic sur la prise OBD, identifier le véhicule et l\'ECU.','Effectuer une lecture complète et enregistrer tous les codes défauts.','Effacer les codes pour vérifier s\'ils réapparaissent au test suivant.']),etape('Analyse des Paramètres (PIDs)', '40 min', ['Sélectionner une liste de paramètres pertinents pour le symptôme observé.','Observer les valeurs au ralenti, puis en charge (essai routier ou accélération).','Comparer les valeurs aux données de référence de la RTA.']),etape('Validation du Diagnostic', '15 min', ['Reproduire les conditions d\'apparition du défaut.','Effectuer une nouvelle lecture des codes défauts.'])], securiteRangement:['Maintenir la charge de la batterie','Déconnecter proprement l\'outil de diagnostic','Archiver les journaux de diagnostic (logs)'], pointsCles:['Lecture des codes défauts','Analyse des paramètres pertinents','Validation par reproduction du défaut'] },
  33:{ id: 33, duree:'2h00', titre:'MA 210 • Identification structurelle du système d\'injection', situation:'Afin de pouvoir intervenir efficacement sur n\'importe quel système d\'injection, vous devez apprendre à identifier rapidement sa structure, ses capteurs et ses actionneurs.', objectif:'Localiser capteurs/actionneurs et flux air/carburant pour préparer une intervention. (Compétence C2.1)', materiel:['Schémas de systèmes d\'injection','Photos de moteurs','Étiquettes de repérage','Documentation technique (RTA)'], 
    etudePrelim:[
        {type: 'qcm', q:"Quel est le capteur le plus important pour que le calculateur puisse déterminer le moment précis de l'injection et de l'allumage ?", options: ["Le capteur de température d'eau", "Le capteur de position du vilebrequin (PMH)", "La sonde lambda"], r:"Le capteur de position du vilebrequin (PMH)"},
        {type: 'text', q:"Réflexion : Sur un moteur diesel Common Rail, situez le régulateur de pression. Pourquoi est-il un élément si crucial pour le bon fonctionnement du moteur ?",r:'Il est généralement situé sur la pompe haute pression ou sur la rampe commune. Il est crucial car il ajuste en temps réel la pression du carburant, qui influence directement la puissance, la consommation et les émissions.'},
        {type: 'text', q:"Analyse de système : Suivez le chemin de l'air sur un moteur essence turbocompressé : du filtre à air jusqu'à la soupape d'admission, en listant les composants clés rencontrés.",r:'Filtre à air → Débitmètre → Turbo (partie compresseur) → Échangeur (intercooler) → Boîtier papillon → Collecteur d\'admission → Soupape d\'admission.'}
    ], 
    activitePratique:[ etape('Analyse Système Essence', '50 min', ['Identifier l\'ECU, la rampe d\'injection et les injecteurs.','Localiser le débitmètre (MAF) ou capteur de pression (MAP), et les sondes lambda.','Repérer le boîtier papillon motorisé et le système d\'allumage.']),etape('Analyse Système Diesel', '50 min', ['Identifier la pompe haute pression, le rail commun et les injecteurs.','Localiser les capteurs PMH et AAC, indispensables au séquencement.','Repérer la vanne EGR et les capteurs du FAP (pression différentielle).'])], securiteRangement:['Ne jamais débrancher de composant moteur tournant','Protéger les connecteurs lors des interventions','Archiver les schémas étudiés'], pointsCles:['Cartographie mentale du système','Connaître les noms exacts des composants','Comprendre les flux d\'air et de carburant'] },
  34:{ id: 34, duree:'2h30', titre:'MA 204 • Diagnostic système injection essence', situation:'Un véhicule essence présente un manque de puissance et le témoin moteur est allumé. Vous devez mener un diagnostic complet du système d\'injection.', objectif:'Lier DTC/PIDs à des tests capteurs/actionneurs et réparer. (Compétence C2.1)', materiel:['Valise de diagnostic','Multimètre','Oscilloscope','Manomètre de pression essence'], 
    etudePrelim:[
        {type: 'text', q:"Méthodologie : La valise affiche 'P0171 - Système trop pauvre'. Listez 3 causes possibles, allant de la plus simple à la plus complexe, et expliquez comment les tester.",r:'1. Prise d\'air à l\'admission (test avec fumigène). 2. Pompe à essence faible ou filtre colmaté (test de pression/débit). 3. Injecteur bouché ou débitmètre défectueux (test des paramètres).'},
        {type: 'qcm', q:"La sonde lambda amont reste bloquée à 0.1V. Le mélange est-il riche ou pauvre ? Le calculateur va-t-il essayer d'enrichir ou d'appauvrir ?", options: ["Riche / Il va appauvrir", "Pauvre / Il va enrichir", "Normal / Il ne fait rien"], r:"Pauvre / Il va enrichir"},
        {type: 'text', q:"Scénario : Le moteur cale au ralenti, mais fonctionne bien à haut régime. Quel capteur est le plus probablement en cause ?",r:'Le régulateur de ralenti ou le boîtier papillon motorisé.'}
    ], 
    activitePratique:[ etape('Lecture et Analyse Initiale', '30 min', ['Lire les codes défauts (DTC) et les données figées (freeze frame).','Analyser les paramètres clés : MAF/MAP, ratio lambda, pression de rampe (FRP).','Effacer les codes et effectuer un test pour voir ce qui revient.']),etape('Contrôle des Capteurs', '60 min', ['Mesurer la tension du débitmètre d\'air.','Vérifier la cohérence du capteur de pression d\'admission par rapport à la dépression.','Contrôler le signal des sondes lambda amont et aval.','Visualiser les signaux des capteurs PMH et AAC à l\'oscilloscope.']),etape('Contrôle des Actionneurs', '40 min', ['Mesurer la résistance et le signal de commande des injecteurs.','Tester le fonctionnement du boîtier papillon motorisé et de la vanne EGR.','Vérifier le régulateur de pression de carburant.'])], securiteRangement:['Effectuer les déconnexions proprement','Ranger les appareils de mesure après usage','Tracer toutes les étapes du diagnostic'], pointsCles:['Corrélation DTC et paramètres','Les capteurs confirment le symptôme','Les actionneurs valident la panne'] },
  35:{ id: 35, duree:'2h00', titre:'ME 202 • Contrôle du circuit d\'allumage', situation:'Un véhicule essence a des ratés à l\'accélération. Le diagnostic s\'oriente vers le circuit d\'allumage. Vous devez contrôler les bougies, câbles et bobines.', objectif:'Diagnostiquer les ratés, réparer et valider l\'étincelle. (Compétence C2.3)', materiel:['Multimètre','Oscilloscope','Clé à bougie dynamométrique','Testeur d\'étincelle'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de panne : Un code 'P0302 - Raté d'allumage Cylindre 2' est enregistré. Décrivez la méthode la plus rapide pour déterminer si la panne vient de la bougie ou de la bobine.",r:'Inverser la bobine du cylindre 2 avec celle d\'un autre cylindre (ex: le 3). Effacer le défaut et refaire un test. Si le défaut se déplace en P0303, c\'est la bobine. Sinon, c\'est probablement la bougie.'},
        {type: 'qcm', q:"Vous observez une bougie dont l'isolant est fendu et présente des traces noires. Quelle est la cause probable de ce défaut ?", options: ["L'essence est de mauvaise qualité", "C'est de l'usure normale", "Un arc électrique s'est formé à l'extérieur de la bougie (défaut d'isolement)"], r:"Un arc électrique s'est formé à l'extérieur de la bougie (défaut d'isolement)"},
        {type: 'text', q:"Analyse de signal : À l'oscilloscope, la tension de l'étincelle sur un cylindre est beaucoup plus élevée que sur les autres. Qu'est-ce que cela indique sur l'état de la bougie ou du circuit ?",r:'Cela indique une résistance élevée dans le circuit secondaire : écartement des électrodes de la bougie trop grand, ou câble haute tension défectueux.'}
    ], 
    activitePratique:[ etape('Pré-Diagnostic', '20 min', ['Lire les codes défauts (ex: P030x pour raté d\'allumage).','Inspecter visuellement les bougies et les bobines.','Écouter le moteur au ralenti pour détecter les ratés.']), etape('Contrôle des Bobines', '45 min', ['Mesurer les résistances des enroulements primaire et secondaire.','Vérifier l\'isolement.','Visualiser le signal de commande primaire à l\'oscilloscope.','Effectuer un test d\'étincelle.']),etape('Contrôle des Bougies', '40 min', ['Inspecter l\'état des électrodes et mesurer l\'écartement.','Analyser la couleur (indice de richesse).','Remplacer les bougies défectueuses en respectant le couple de serrage.'])], securiteRangement:['Attention à la haute tension (HT)','Respecter les couples de serrage des bougies','Tracer le diagnostic'], pointsCles:['Bobine fonctionnelle','Bougie en bon état','Analyse des courbes à l\'oscilloscope'] },
  36:{ id: 36, duree:'1h45', titre:'ME 203 • Contrôle du circuit de pré-post chauffage', situation:'Un moteur diesel démarre mal à froid et fume blanc. Vous devez contrôler le circuit de préchauffage pour trouver la cause.', objectif:'Tester les bougies, relais et temporisation puis effectuer le réglage. (Compétence C2.3)', materiel:['Multimètre','Pince ampèremétrique','Chronomètre','Schéma électrique'], 
    etudePrelim:[
        {type: 'qcm', q:"Le moteur démarre mal mais le témoin de préchauffage s'allume correctement. Quelle est votre première hypothèse de diagnostic ?", options: ["Le calculateur est HS", "Une ou plusieurs bougies de préchauffage sont grillées", "La batterie est neuve"], r:"Une ou plusieurs bougies de préchauffage sont grillées"},
        {type: 'text', q:"Scénario : Vous mesurez une intensité totale de 30A sur un moteur 4 cylindres. Est-ce cohérent ? Combien de bougies sont probablement défectueuses ?",r:'Non, ce n\'est pas cohérent. Une bougie consomme environ 10-15A. Pour 4 cylindres, on attend 40-60A. Avec 30A, il y a probablement une bougie de défectueuse (voire deux).'},
        {type: 'text', q:"Réflexion : Quel est le rôle du 'post-chauffage' (maintien des bougies allumées après le démarrage) sur la pollution et le bruit du moteur à froid ?",r:'Il aide à stabiliser la combustion lorsque le moteur est froid, ce qui réduit les émissions de polluants (imbrûlés) et les claquements caractéristiques du diesel à froid.'}
    ], 
    activitePratique:[ etape('Contrôle du Circuit Global', '35 min', ['Vérifier l\'allumage du voyant au tableau de bord et son temps.','Mesurer la tension sur la barre d\'alimentation des bougies.','Mesurer l\'intensité totale consommée par le circuit.']),etape('Contrôle des Bougies', '45 min', ['Mesurer la résistance de chaque bougie.','Mesurer l\'intensité individuelle de chaque bougie.','Inspecter visuellement l\'extrémité des bougies.']),etape('Contrôle du Boîtier de Préchauffage', '20 min', ['Vérifier l\'activation et la commande du relais.','Contrôler le maintien de la tension en post-chauffage.'])], securiteRangement:['Débrancher la batterie avant dépose','Respecter les couples de serrage','Tracer les mesures'], pointsCles:['Homogénéité des bougies','Commande fonctionnelle','Temporisation conforme'] },
  37:{ id: 37, duree:'2h00', titre:'MP 201 • Analyser les gaz d\'échappement essence et diesel', situation:'Dans le cadre d\'un diagnostic pollution, vous devez utiliser l\'analyseur de gaz et l\'opacimètre pour évaluer les émissions d\'un véhicule.', objectif:'Comparer aux normes, cibler l’organe défaillant et effectuer un contrôle qualité. (Compétence C2.4)', materiel:['Analyseur 4/5 gaz','Opacimètre','Thermomètre infrarouge','Documentation technique (RTA)'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de données (essence) : CO > 3%, HC élevés, Lambda < 1. Le mélange est-il riche ou pauvre ? Citez deux causes possibles.",r:'Le mélange est riche. Causes possibles : sonde lambda défectueuse, injecteur qui fuit, pression de carburant trop élevée.'},
        {type: 'qcm', q:"Analyse de données (diesel) : L'opacité est très élevée. Quelle est la cause la plus probable ?", options: ["L'huile est trop vieille", "L'injection est défectueuse (injecteur, pompe) ou l'admission d'air est obstruée (filtre à air, EGR bloquée ouverte)", "Les pneus sont sous-gonflés"], r:"L'injection est défectueuse (injecteur, pompe) ou l'admission d'air est obstruée (filtre à air, EGR bloquée ouverte)"},
        {type: 'text', q:"Réflexion critique : Pourquoi un catalyseur ne peut-il pas fonctionner correctement si la régulation lambda est défaillante en amont ?",r:'Le catalyseur a besoin d\'un mélange stœchiométrique (lambda=1) pour fonctionner. Si le mélange est trop riche ou trop pauvre, les réactions chimiques de traitement des gaz ne peuvent pas se faire efficacement.'}
    ], 
    activitePratique:[ etape('Analyse sur Moteur Essence', '50 min', ['Faire chauffer le moteur et le catalyseur.','Effectuer les mesures au ralenti, puis au ralenti accéléré (2500 tr/min).','Analyser les valeurs de CO, HC, O2, CO2 et lambda.']),etape('Analyse sur Moteur Diesel', '50 min', ['Utiliser l\'opacimètre pour mesurer l\'opacité des fumées (test en 3 accélérations).','Analyser la valeur K (m-1) ou le pourcentage d\'opacité.','Interpréter les graphiques d\'accélération.'])], securiteRangement:['Assurer une bonne ventilation de l\'atelier','Nettoyer les sondes des appareils après usage','Archiver les tickets de résultats'], pointsCles:['Valeurs CO/HC/Lambda','Opacité des fumées','Identification de l\'organe ciblé'] },
  38:{ id: 38, duree:'1h30', titre:'MP 202 • Contrôle des sondes lambda', situation:'Le témoin moteur est allumé et le diagnostic pointe vers un défaut sur les sondes lambda. Vous devez les contrôler pour valider le diagnostic.', objectif:'Vérifier oscillations, temps de réponse et effectuer les réglages. (Compétence C2.2)', materiel:['Valise de diagnostic','Oscilloscope','Multimètre','Clé à sonde lambda'], 
    etudePrelim:[
        {type: 'text', q:"Analyse de signal : À l'oscilloscope, le signal de la sonde amont varie lentement, prenant plus d'une seconde pour passer de 0.2V à 0.8V. Quel est le diagnostic pour cette sonde ?",r:'La sonde est \'vieillissante\' ou \'paresseuse\'. Elle ne réagit plus assez vite aux changements de richesse, ce qui nuit à la régulation et à la consommation.'},
        {type: 'qcm', q:"La sonde aval oscille de la même manière que la sonde amont. Quelle est la conclusion sur l'état du catalyseur ?", options: ["Le catalyseur fonctionne parfaitement", "Le catalyseur est HS, il ne traite plus les gaz.", "C'est un problème de sonde"], r:"Le catalyseur est HS, il ne traite plus les gaz."},
        {type: 'text', q:"Réflexion : Pourquoi la sonde doit-elle être chauffée pour fonctionner correctement ? Quelle information supplémentaire vous donne la mesure de la résistance de son circuit de chauffage ?",r:'L\'élément sensible de la sonde (zircone) ne devient conducteur d\'ions oxygène qu\'à partir de 300°C. La mesure de la résistance permet de vérifier si l\'élément chauffant interne n\'est pas coupé.'}
    ], 
    activitePratique:[ etape('Lecture des Paramètres', '25 min', ['Observer les signaux des sondes amont et aval via l\'outil de diagnostic.','Vérifier que la boucle de régulation est fermée à chaud.','Effectuer des tests d\'enrichissement / appauvrissement.']),etape('Mesures Physiques', '35 min', ['Visualiser le signal de la sonde amont à l\'oscilloscope (pentes nettes).','Mesurer la résistance et l\'alimentation du réchauffeur de sonde.','Vérifier que le signal de la sonde aval est stable si le catalyseur est efficace.']),etape('Diagnostic Final', '25 min', ['Une sonde amont lente ou non réactive doit être remplacée.','Une sonde aval qui oscille indique un catalyseur hors service.'])], securiteRangement:['Prudence avec l\'échappement chaud','Respecter le couple de serrage de la sonde','Tracer les signaux observés'], pointsCles:['Sonde amont oscille','Sonde aval contrôle le catalyseur','Temps de réponse de la sonde'] }
};

    

    
