import { students } from '@/lib/mock-data';
import { notFound } from 'next/navigation';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { BarChart, BrainCircuit, Check, ListTree, User } from 'lucide-react';
import { Separator } from '@/components/ui/separator';
import { analyzeSkillGaps } from '@/ai/flows/skill-gap-analysis';
import { Badge } from '@/components/ui/badge';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { ChevronLeft } from 'lucide-react';

async function SkillGapAnalysis({ student }: { student: (typeof students)[0] }) {
  const analysis = await analyzeSkillGaps({ studentPerformanceData: student.performanceData });

  return (
    <Card className="bg-primary/5 border-primary/20">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 font-headline tracking-wider text-2xl">
          <BrainCircuit className="text-primary" />
          AI Skill Gap Analysis
        </CardTitle>
        <CardDescription>
          Personalized insights and learning paths generated by AI based on performance data.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div>
          <h3 className="font-semibold flex items-center gap-2 mb-2"><BarChart className="w-4 h-4"/>Identified Skill Gaps</h3>
          <p className="text-muted-foreground">{analysis.identifiedSkillGaps}</p>
        </div>
        <div>
          <h3 className="font-semibold flex items-center gap-2 mb-2"><ListTree className="w-4 h-4"/>Suggested Learning Paths</h3>
          <p className="text-muted-foreground">{analysis.suggestedLearningPaths}</p>
        </div>
      </CardContent>
    </Card>
  );
}

export default function StudentDetailPage({ params }: { params: { id: string } }) {
  const student = students.find((s) => s.id === params.id);

  if (!student) {
    notFound();
  }

  return (
    <div className="space-y-8">
      <Button asChild variant="outline" size="sm" className="mb-4">
        <Link href="/teacher/dashboard/students">
            <ChevronLeft className="mr-2 h-4 w-4" />
            Back to Roster
        </Link>
      </Button>
      <div className="flex flex-col md:flex-row items-start gap-8">
        <Card className="w-full md:w-1/3">
          <CardHeader className="items-center text-center">
            <Avatar className="w-24 h-24 mb-4">
              <AvatarImage src={student.avatar} alt={student.name} data-ai-hint="person portrait"/>
              <AvatarFallback><User className="w-12 h-12" /></AvatarFallback>
            </Avatar>
            <CardTitle className="font-headline text-4xl tracking-wider">{student.name}</CardTitle>
            <CardDescription>{student.email}</CardDescription>
          </CardHeader>
          <CardContent className="text-center">
             <Separator className="my-4"/>
             <div className="space-y-4">
                <div>
                    <p className="text-sm text-muted-foreground">Overall Progress</p>
                    <div className="flex items-center gap-2 justify-center">
                        <Progress value={student.progress} className="w-3/4" />
                        <span className="text-sm font-bold">{student.progress}%</span>
                    </div>
                </div>
                <div>
                    <p className="text-sm text-muted-foreground">Last Active</p>
                    <p className="font-semibold">{student.lastActive}</p>
                </div>
             </div>
          </CardContent>
        </Card>
        <div className="w-full md:w-2/3 space-y-6">
            <Card>
                <CardHeader>
                    <CardTitle>Performance Summary</CardTitle>
                </CardHeader>
                <CardContent>
                    <p className="text-muted-foreground whitespace-pre-wrap">{student.performanceData}</p>
                </CardContent>
            </Card>

            <SkillGapAnalysis student={student} />
        </div>
      </div>
    </div>
  );
}
